### ISSUE TITLE
Linear to Linear import?

### ISSUE THREAD

**Issue by hirusi** [linear/linear#122]
Be able to use the Import CLI to transfer an entire team to another workspace.

**Comment by rlargman** [comment]
@hirusi you should be able to do this, we do now have a Linear to Linear importer. Is it not working for you?

**Comment by hirusi** [comment]
As I can see from [the import package's readme](https://github.com/linear/linear/tree/master/packages/import):

![image](https://user-images.githubusercontent.com/3974019/127963982-f0e77999-f600-417e-a1fe-1a60c8dd70b9.png)

It is a very basic export. I need to move an entire team to another account. I signed up personally to test Linear, and now I need to move the team to my workplace's account since I have done a lot of "organizing" work after using the Trello CSV import.

**Comment by rlargman** [comment]
@hirusi What other fields did you want added? We don't currently have plans to add additional functionality to the Linear CSV    importer, but feel free to add on to the fields that are supported. We welcome any pull requests.
