### ISSUE TITLE
ASANA - Import feature request: Levels

### ISSUE THREAD

**Issue by jeremy-webb** [linear/linear#123]
The current importer only takes tasks at their top _level_, meaning if those issues have subtasks, or subtask-subtasks, etc they're ignored :(

**Assuming that _level_ is the terminology based on an Asana `.csv` export.

**Comment by aspiers** [comment]
Yes, parent/child task relationships really need to be preserved.

**Comment by erinfrey** [comment]
We just added support so that Asana sub-tasks are imported as a checklist on the parent issue. Thanks for the feedback!
