### ISSUE TITLE
Import from GitLab issues CSV

### ISSUE THREAD

**Issue by adrm** [linear/linear#139]
GitLab allows exporting all issues in CSV format. We are eyeing moving from GitLab issues to Linear, so a way to import all of our open issues to Linear would be a great timesaver if we choose to migrate. In fact, the workload that would mean to migrate without an importer is one of the reasons we have not migrated yet.

Is there a plan to support importing GitLab issues automatically from the app or through this CLI importer?

**Comment by rlargman** [comment]
@adrm We don't currently have a GitLab importer on the roadmap, but I've noted your feedback. However, we welcome pull requests, so if you would like to build a GitLab importer feel free to make a pull request with your code.
