### ISSUE TITLE
Issues.filter returning wrong results for `eq` filter

### ISSUE THREAD

**Issue by arseniocosta1** [linear/linear#153]
## Description

When executing the following GQL query:

```gql
query GetIssues{
    issues(
        last: 10,
        orderBy: updatedAt
        filter: {updatedAt: {gt: "2021-06-16T17:05:26.997Z"}}) {
        nodes {
            id
            identifier
            updatedAt
        }
    }
}
```

Im getting an issue with that exact timestamp:

![CleanShot 2021-09-21 at 16 11 46](https://user-images.githubusercontent.com/58417070/134197806-c27e17b5-a3a2-43db-affa-210f1bd831d9.png)

As one can see its not respecting the semantics of the `gt` constraint

https://github.com/linear/linear/blob/7ed69001fbad36c57c4112626cf03dde8ffce9bd/packages/sdk/src/schema.graphql#L1080

Note: This is an issue with the underlying server implementation.
And not with this SDK client-generated client, as such, I'm not sure this is the right place to report it, please forward me to the proper place in case this is not it

**Comment by eldh** [comment]
Thanks for reporting! We'll have a look.

**Comment by artman** [comment]
Dates in the database had finer precision then what the API supported. Dates are now truncated to the closest milliseconds, so the above queries now work as expected.

**Comment by arseniocosta1** [comment]
@artman Thanks for the quick resolution ⭐
