### ISSUE TITLE
Import feature request: ClickUp

### ISSUE THREAD

**Issue by patrys** [linear/linear#154]
I love the software and follow its progress but I can't hope to ever switch until an importer is available for ClickUp.

I'd be fine with lists and folders being converted to tags or anything else that allows me to re-create the structure in Linear.

**Comment by rlargman** [comment]
I've made a note of your feedback. We don't currently have concrete plans to make an importer for ClickUp, but it's something we can consider for the future. We also welcome pull requests, so if you would like to make a ClickUp importer based on the others in the repo, we'd be happy to review.

**Comment by de-ar** [comment]
@rlargman A friend of mine is a full time ClickUp user and has had it enough with their product. I needed to write this for him, I thought I might as well contribute to the repo. I look but didn't find anything relevant to contributing. Are there any instructions that I should keep in mind?

I'm pushing it in #220

**Comment by AndryHTC** [comment]
@de-ar in the last year I've collaborated with 3 big companies that wants to move away from ClickUp.

I think your work will be helpful for many, as a starting point to use Linear

**Comment by evaneykelen** [comment]
@de-ar I'm interested to give the ClickUp importer a spin!

**Comment by arndeash** [comment]
where you able to do any progress here @de-ar ?
