### ISSUE TITLE
Estimates is missing in generated sdk

### ISSUE THREAD

**Issue by sergey-lapin** [linear/linear#164]
Hello, I am big fan of your product, really appreciate how well structured it is. 
Was looking for estimates feature in sdk seems that it is not there. 
Any plans to add it to sdk?

**Comment by eldh** [comment]
Hi! Not sure what you mean exactly. Estimates are available on issues and the different estimation settings are available on teams. Could you provide some more context on what you want to achieve?

**Comment by sergey-lapin** [comment]
@eldh I see, estimate is just number on the issue. I was looking for a separate type, like Cycle or IssueLabel, but I guess there is no need for that, makes sense. Closing.

**Comment by eldh** [comment]
Yeah, it's just a number, which get's converted to what's displayed in the app based on the settings for the team.
