### ISSUE TITLE
publish the packages: codegen-doc, codegen-sdk and codegen-test on npm as well

### ISSUE THREAD

**Issue by MoritzGruber** [linear/linear#167]
hello guys,
we are very happy customers of linear. Thank you for the great work you do. That's how I stumbled across your documentation and this repo. Well, we also use graphql for our product. I think your approach to generating the SDK is very clever. I would like to use a part of the package that you have written here for our product. I am mainly interested in @linear/codegen-doc. Legally, it is no problem with a MIT licence. But it's a bit cumbersome to copy your code or to fork the whole repo (especially if only one package from the monorepo here is reused). Therefore, it would be great if you could publish the packages: codegen-doc, codegen-sdk and codegen-test on npm as well.

Thanks much!
Moritz

**Comment by pacocoursey** [comment]
Hey, no plans to do this atm but I'll re-open if we consider it.
