### ISSUE TITLE
Command not found after install

### ISSUE THREAD

**Issue by brianedelman** [linear/linear#178]
Getting command not found after running `yarn global add @linear/import` and then running `linear-import`. I have opened a new terminal and tried again with no luck. I have confirmed by running `yarn list` that it is present as a package.

**Comment by pacocoursey** [comment]
This sounds like an issue with your command line environment or yarn version.

Can you try [installing the latest yarn](https://classic.yarnpkg.com/lang/en/docs/cli/self-update/), clearing the cache `yarn cache clean`, removing the global package `yarn global remove @linear/import`, then re-installing the latest version `yarn global add @linear/import@latest`?

**Comment by anfuca** [comment]
> This sounds like an issue with your command line environment or yarn version.
> 
> Can you try [installing the latest yarn](https://classic.yarnpkg.com/lang/en/docs/cli/self-update/), removing the global package `yarn global remove @linear/import`, clearing the cache `yarn cache clean`, then re-installing the latest version `yarn global add @linear/import@latest`?

Thanks. I ended using `npm` instead and it worked.
