### ISSUE TITLE
missing API for deleting labels

### ISSUE THREAD

**Issue by dwelle** [linear/linear#180]
Currently, the SDK only allows for label archival via `issueLabelArchive()`, but no permanent removal. The problem with archival is that you currently 1) can't unarchive a label 2) can't create a new label with the same name.

The problem (2) apparently isn't even handled, as creating a label with a name of a duplicate, archived label results in an Internal server error in the SDK, and this error in the UI:

![image](https://user-images.githubusercontent.com/5153846/159179170-7c9f891d-a2cb-4b1e-b2ff-93212630f577.png)

#### Proposal:

- expose `issueLabelDelete()` on the SDK
- support un-archiving a label via the SDK (if there's even a good reason for supporting archival in the first place)

---

I encountered this issue when writing a custom importer. This label issue makes it slightly more complicated.

**Comment by pacocoursey** [comment]
Hi @dwelle, sorry for the late response here. You may have already seen, but the `issueLabelDelete` mutation is now available.
