### ISSUE TITLE
Weird app icon on Windows

### ISSUE THREAD

**Issue by aetinx** [linear/linear#186]
On Windows 11, Linear uses a Big Sur icon, which is Apple's style, not Windows'. Also, the icon is very small compared to other app icons on the taskbar.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/65425469/162226029-7befccbb-fa15-4b8e-814e-cc0382459d35.png">

**Comment by eldh** [comment]
Thanks, we'll see if we can improve this.
