### ISSUE TITLE
The GitHub importer duplicates/re-imports issues every time

### ISSUE THREAD

**Issue by grahamc** [linear/linear#188]
The CLI interface produces duplicates of issues on import:

![image](https://user-images.githubusercontent.com/76716/162976480-1d5ed12a-9e60-4f4e-9668-3ccfa39de9bc.png)

Notably, the website's importer detects already imported issues and won't import them again:

![image](https://user-images.githubusercontent.com/76716/162976229-d6c46131-9b55-40d0-b30a-65a058580d9c.png)

I'd like to run this importer across a few dozen repositories on a regular basis, and duplicating the issues on every import makes that not feasible.

The development history of the importers sort of looks like it is an exported version of the closed source version used by the website. If this is (optimistically) the case, maybe this issue (and #189) would be easy to close?

**Comment by rlargman** [comment]
Similar to issue #189. Unfortunately, the CLI importers are not exported versions of the closed source versions, so making these changes would not be simple. However, if you want to make changes, we welcome pull requests (although I'm a bit behind on reviewing currently 😬 )
