### ISSUE TITLE
The GitHub importer can't match owners like the website can

### ISSUE THREAD

**Issue by grahamc** [linear/linear#189]
The GitHub importer asks to assign all of the issues to one person or nobody. In comparison, the website's importer supports mapping issues to people in the team. I'd like to run this importer across a few dozen repositories on a regular basis, which makes this tricky.

**Comment by rlargman** [comment]
@grahamc Our in app importer does have features that our CLI importer doesn't have as it's newer and we suggest using the in app importer in general. In general, we are unlikely to keep feature parity between these two versions of the importer, and don't recommend continual syncing. You could try [this](https://linear-sync.com/) out though ([and this is the open source version](https://github.com/jtormey/linear-sync)).
