### ISSUE TITLE
Cycle docs say "percentage done" is points not issue count, but may be wrong?

### ISSUE THREAD

**Issue by gimbo** [linear/linear#199]
Not sure if this is the right place to report this or not, but I _think_ there's a mismatch between the Linear docs and the app itself.

Specifically on the "Use Cycles" page, in the FAQ, under ["What does the percentage mean?"](https://linear.app/docs/use-cycles?collapsible=ef774fa2b31f), which begins:

> The percentage success reflects the percent of estimated work completed in the cycle. The percentage is based on estimations, not the amount of issues. If the estimations are not enabled, each issue counts as 1. 

(BTW because of the collapse/expand widgetry there —  which seems a bit superfluous to me TBH — I couldn't copy/paste that text directly.)

For completed cycles this may be right, but for my current cycle, it doesn't appear to be. E.g. here's a screenshot of my current cycle:

![Screenshot 2022-05-18 at 13 00 53](https://user-images.githubusercontent.com/133770/169034454-d423656d-16cf-4500-8b12-0f73cbe062c2.png)

* There are 21 issues, of which 4 are done; 4/21 ≈ 19%
* Total points is 59, of which done issues account for 10 points; 10/59 = 0.169 ≈ 17%

So it looks to me like the estimate percentage done is 17% not 19%, but 19% is shown. (The "All cycles" view also shows this, as "19% progress".)

As I missing/misunderstanding something, or are the docs wrong? (Or is the app wrong?)

Many thanks!

**Comment by pacocoursey** [comment]
Hey @gimbo – the done calculation takes into account issues that are "In Progress", counting them as 0.25% of a Done issue. That can account for differences in the graph and cycle calculations.

If you need more help please join us at the Slack community, where we can respond a lot faster to product questions:
https://linear.app/docs/tutorials#slack-community
