### ISSUE TITLE
Error: Could not find anonymous context param for mutation issuePriorityValues

### ISSUE THREAD

**Issue by briward** [linear/linear#201]
Hi,

I'm currently getting the following error:

```
Error: Could not find anonymous context param for mutation issuePriorityValues
```

I haven't changed anything in my code but it appears to have broken somehow, as it originally worked fine. Could this be a data issue perhaps or has there been a change to the API? 

My code looks as follows:

```ts
import { LinearClient } from '@linear/sdk';
...
this.linear = new LinearClient({ apiKey: process.env.LINEAR_KEY });
...
const priorities = await this.linear.issuePriorityValues;
```

Thanks in advance for looking into it ! 

---

Version of SDK: `1.22.0`
Node version: `v14.19.3`

**Comment by eldh** [comment]
Hey! I think this should be fixed now. Sorry about the bug!
