### ISSUE TITLE
Mapping Status to list when importing from Trello

### ISSUE THREAD

**Issue by huksley** [linear/linear#204]
I imported my cards as issues to Linear from Trello, but they all end up having status "Backlog"
is there any way to map Trello list (lane) to the issue status?

I have it rather straightforward is that there is almost 1-to-1 matching

<img width="1685" alt="Screenshot 2022-06-16 at 2 16 30 PM" src="https://user-images.githubusercontent.com/1594349/174058641-959cfb5e-cc3a-4b10-bc59-dac38d871074.png">

**Comment by hmnd** [comment]
Would be a great feature addition...

**Comment by hmnd** [comment]
@huksley I've fixed this in #337 :)

**Comment by macintushar** [comment]
@pacocoursey we are facing a need for this as we need to migrate our Trello board to Linear, is it possible to get someone to review @hmnd's work and get this merged?
