### ISSUE TITLE
TypeError: i.comments is not a function

### ISSUE THREAD

**Issue by abbysrc** [linear/linear#208]
I'm trying to use TypeScript and your SDK to create a link for our use case between our Discord application and Linear. Here's my code, very hacky as I couldn't quite get the hang of your typing system and VSCode decided it wanted to interfere and make it worse:
```js
const issues = await linearClient.issues();
    const issuesList = (issues["nodes"] as unknown as Issue[])

    for (const issue in issuesList) {
        const i = issue as unknown as Issue;
        const comments = await i.comments();
        const commentsList = (comments["nodes"] as unknown as Comment[])
        for (const comment in commentsList) {
            const c = comment as unknown as Comment;
            const message = c.body;

            const poster = await c.user!;
            const username = poster.displayName;
            const fullname = poster.name;

            const id = i.description!.split("\n")[3].split(" ")[2];

            discordClient.guilds.cache.get("941635270766366740")!
                .members.cache.get(id)!
                .send({
                    embeds: [                
                        new EmbedBuilder()
                            .setTitle("🎫 You got a response to your ticket!")
                            .setDescription(`${fullname} (${username}) has responded to your ticket:\n\`${message}\``)
                            .setColor(15051531)
                            .toJSON()
                    ]
                })
        }
    }
```

The line referenced in the error is `const comments = await i.comments()`. When I log the issue to console, it doesn't have a `comments()` method. What am I doing wrong?

**Comment by pacocoursey** [comment]
Hey @abbysrc, `linearClient.issues` does not return issues directly, rather `IssueConnections`. Seems like the VSCode setup is being hindering here. Check out our GraphQL schema reference for this method to understand more:

https://studio.apollographql.com/public/Linear-API/schema/reference/objects/Query?variant=current#issues
