### ISSUE TITLE
Chrome devtools in production

### ISSUE THREAD

**Issue by quavious** [linear/linear#212]
# Description
I know many applications like Notion, Slack, based on Electron framework, prohibit opening Chrome devtools in production. But I could access this screen by entering Ctrl + Shift + I.
Is this action intented?
## Screenshot
![linear](https://user-images.githubusercontent.com/25116473/184464902-e686e910-53c4-4841-95d0-7e3c958436f9.PNG)

**Comment by pacocoursey** [comment]
Yep, we don't disable DevTools and have no current plans to do so.
