### ISSUE TITLE
Keep existing JIRA ticket number (without prefix)  after imported

### ISSUE THREAD

**Issue by LeeU1911** [linear/linear#213]
Hey all,

I recently import JIRA tickets to Linear and saw the numbers reset. This creates a bit of frustration because team is still using the old JIRA numbers for ongoing tickets. Would be great if Linear can keep ticket numbers consistent (without the prefix change if any) so on-going tickets reference will be much easier

Thank you

**Comment by tommoor** [comment]
This is now the case where possible, the import must be into a fresh team without any other issues.
