### ISSUE TITLE
API mismatch between SDK and GraphQL versions. 

### ISSUE THREAD

**Issue by simon-mo** [linear/linear#214]
Hi there! 
I was using the npm package and noticed that some fields in the documentation is not included.

For example, the generated SDK code for `CycleFilter` is 
```typescript
/** [Alpha] Project filtering options. */
export declare type CycleFilter = {
    /** Compound filters, all of which need to be matched by the cycle. */
    and?: Maybe<Array<CycleFilter>>;
    /** Comparator for the cycle completed at date. */
    completedAt?: Maybe<DateComparator>;
    /** Comparator for the created at date. */
    createdAt?: Maybe<DateComparator>;
    /** Comparator for the cycle ends at date. */
    endsAt?: Maybe<DateComparator>;
    /** Comparator for the identifier. */
    id?: Maybe<IdComparator>;
    /** Filters that the cycles issues must satisfy. */
    issues?: Maybe<IssueCollectionFilter>;
    /** Comparator for the cycle name. */
    name?: Maybe<StringComparator>;
    /** Comparator for the cycle number. */
    number?: Maybe<NumberComparator>;
    /** Compound filters, one of which need to be matched by the cycle. */
    or?: Maybe<Array<CycleFilter>>;
    /** Comparator for the cycle start date. */
    startsAt?: Maybe<DateComparator>;
    /** Filters that the cycles team must satisfy. */
    team?: Maybe<TeamFilter>;
    /** Comparator for the updated at date. */
    updatedAt?: Maybe<DateComparator>;
};
```

But the documentation also mentioned an `isActive` field: https://studio.apollographql.com/public/Linear-API/schema/reference/inputs/CycleFilter?variant=current#isActive

Is there a way to utilize this updated API?

(so far I can get around this by fetching all cycles and perform local filter.)

**Comment by eldh** [comment]
Yeah, this will be added in the next SDK release.

**Comment by simon-mo** [comment]
Is there a rough timeline for SDK releases? Just want to check whether I should keep using existing workaround for my workflow or wait for release before running it "in prod"

**Comment by eldh** [comment]
We're hoping to get a new version out in the coming days.

**Comment by simon-mo** [comment]
Update, I ended up directly writing GraphQL instead since the workaround is pretty hard to read.
