### ISSUE TITLE
Project updates missing?

### ISSUE THREAD

**Issue by MarioIannotta** [linear/linear#216]
Hey 👋
I'm using the SDK version `1.22.0` and it looks like it is not possible to fetch the project updates for a given project / user.
Am I missing something?

Thanks,
Mario

**Comment by guillaumelachaud** [comment]
Hi 👋 !

We have released version `2.0.0` of the SDK today. It catches up with the latest API updates and project updates are now available.

You can query project updates like this:
```typescript
const project = await client.project("A_PROJECT_UUID");
const projectUpdates = await project.projectUpdates()
```
