### ISSUE TITLE
Applying template to issue removes priority, changes status and removes from cycle

### ISSUE THREAD

**Issue by technicalliy** [linear/linear#218]
Hello! 👋

Recently my team noticed that when we apply a template to an existing issue, the following actions are taken for us:

- The issue is moved to Triage
- The issue is removed from the current cycle
- The issue's priority is removed

I checked the settings for the template -- we don't have it set up to set a priority, and we don't see an option to change whether it moves the issue's status or cycle, so the fact that it automatically updates these seems like a potential bug.

![image](https://user-images.githubusercontent.com/8595926/191362166-9285b432-5858-48f7-8cfe-a57140055d88.png)

**Comment by eldh** [comment]
Hey, thanks for reporting! We'll look into this and report back.

**Comment by suevalov** [comment]
@technicalliy We've improved a logic around applying templates to existing issues, please give it a try and reopen the issue if you've still experiencing problems.
