### ISSUE TITLE
Feature Request: Workspace-wide API keys

### ISSUE THREAD

**Issue by AlexGrafl** [linear/linear#224]
Currently we need to create API keys on developer accounts when accessing the API via GraphQL in i.e. our build steps. This causes some unwanted side-effects (i.e. the users name as the person creating/updating/commenting) and ties a single user to an API request.

Having workspace-wide API keys would allow us to create general purpose API requests based on our workspace without depending on a single user.

**Comment by tommoor** [comment]
This was implemented as part of OAuth `actor` authorization. Find more details here:

https://developers.linear.app/docs/oauth/oauth-actor-authorization
