### ISSUE TITLE
Webhooks result interpretation

### ISSUE THREAD

**Issue by TMoynat** [linear/linear#23]
Hi,
I'm creating an application using linear webhooks and I want to fetch task's assignee. In order to perform this I found the field "assigneeId" but it's obviously not usable.
Is there a solution to recover user's name with this id? What's the best practice?

Thanks,

**Comment by jorilallo** [comment]
Since this question was posted we updated webhooks but I don't remember if we include more information for assignee or not. You can always query the GraphQL API for the user if you have their id:

```GraphQL
query {
  user {
    id
    name
    avatarUrl
  }
}
```
