### ISSUE TITLE
Python SDK

### ISSUE THREAD

**Issue by aiseei** [linear/linear#234]
hI 

Are there any plans to release a Python SDK. It would much appreciated if there is one. 
We love the ease of use and uncluttered UI (vs existing enterprise soln) and being able to work the API's through the SDK would be awesome!

Thanks.

**Comment by eldh** [comment]
No plans right now. We'll be tracking interest for this and re-evaluate in the future.

**Comment by filip-aipl** [comment]
Would love that!

**Comment by ntindle** [comment]
Would also love this
