### ISSUE TITLE
`createAsUser` is missing from types for `IssueCreateInput`

### ISSUE THREAD

**Issue by rijkvanzanten** [linear/linear#235]
The GraphQL API accepts an optional `createAsUser` field for the input of `issueCreate`. However, the SDK is missing this field from it's `IssueCreateInput` type:

![CleanShot 2022-12-16 at 10 46 47@2x](https://user-images.githubusercontent.com/9141017/208136032-56e0913f-7152-4bef-894a-3c9b76e63c35.png)

```ts
export declare type IssueCreateInput = {
    /** The identifier of the user to assign the issue to. */
    assigneeId?: Maybe<Scalars["String"]>;
    /** The position of the issue in its column on the board view. */
    boardOrder?: Maybe<Scalars["Float"]>;
    /** The cycle associated with the issue. */
    cycleId?: Maybe<Scalars["String"]>;
    /** The issue description in markdown format. */
    description?: Maybe<Scalars["String"]>;
    /** The issue description as a Prosemirror document. */
    descriptionData?: Maybe<Scalars["JSON"]>;
    /** The date at which the issue is due. */
    dueDate?: Maybe<Scalars["TimelessDate"]>;
    /** The estimated complexity of the issue. */
    estimate?: Maybe<Scalars["Int"]>;
    /** The identifier. If none is provided, the backend will generate one. */
    id?: Maybe<Scalars["String"]>;
    /** The identifiers of the issue labels associated with this ticket. */
    labelIds?: Maybe<Array<Scalars["String"]>>;
    /** The identifier of the parent issue. */
    parentId?: Maybe<Scalars["String"]>;
    /** The priority of the issue. */
    priority?: Maybe<Scalars["Int"]>;
    /** The project associated with the issue. */
    projectId?: Maybe<Scalars["String"]>;
    /** The comment the issue is referencing. */
    referenceCommentId?: Maybe<Scalars["String"]>;
    /** The position of the issue related to other issues. */
    sortOrder?: Maybe<Scalars["Float"]>;
    /** The team state of the issue. */
    stateId?: Maybe<Scalars["String"]>;
    /** The position of the issue in parent's sub-issue list. */
    subIssueSortOrder?: Maybe<Scalars["Float"]>;
    /** The identifiers of the users subscribing to this ticket. */
    subscriberIds?: Maybe<Array<Scalars["String"]>>;
    /** The identifier or key of the team associated with the issue. */
    teamId: Scalars["String"];
    /** The title of the issue. */
    title: Scalars["String"];
};
```

**Comment by rijkvanzanten** [comment]
There's an automatic PR waiting to be released that includes a changeSet entry that seems to solve for this. Is that release blocked? https://github.com/linear/linear/pull/194

**Comment by eldh** [comment]
Yeah, we're hoping to get a new SDK version out soon.

**Comment by rijkvanzanten** [comment]
> Yeah, we're hoping to get a new SDK version out soon.

'Yeah' as in "Yeah there's a blocker" or "Yeah the fix is already included?" 😄

**Comment by GuillaumeLachaud** [comment]
Release is blocked but the blockers are identified and currently being worked on. I can't promise a specific release date but we'll make sure to update you as soon as we have more visibility.

**Comment by guillaumelachaud** [comment]
We have released a major update today. Updating to version `2.0.0` of the SDK should allow to use the `createAsUser` field.

**Comment by rijkvanzanten** [comment]
> We have released a major update today. Updating to version `2.0.0` of the SDK should allow to use the `createAsUser` field.

Is this online already? Releases show only a release from the import package 🙂  https://github.com/linear/linear/releases

**Comment by guillaumelachaud** [comment]
It's available on NPM. The `2.0.0` release has not been tagged on Github as it had a changelog too long for Github 🙈 .
Github releases will resume normally with the next patch update

**Comment by rijkvanzanten** [comment]
Haha fantastic 🙈  

For others looking for it, here's the list of changes in 2.0:

https://github.com/linear/linear/blob/master/packages/sdk/CHANGELOG.md
