### ISSUE TITLE
Certain types can't be imported

### ISSUE THREAD

**Issue by rijkvanzanten** [linear/linear#236]
I was hoping to be able to do something like:

```js
import type { IssueCreateInput } from '@linear/sdk';

const params: IssueCreateInput = {...};

await linear.issueCreate(params);
```

but that's impossible, as `IssueCreateInput` isn't exported by `@linear/sdk`.

You could theoretically import it from `@linear/sdk/dist/_generated_documents.js`, but that feels a little dangerous, as that path isn't guaranteed to exist in every release.

**Comment by guillaumelachaud** [comment]
I think what you are looking for is the `LinearDocument`:

```typescript
import {LinearClient, LinearDocument} from "@linear/sdk";

 const params: LinearDocument.IssueCreateInput = {
    title: "My new issue",
    teamId: 'TEAM_UUID',
  };
 await client.createIssue(params);
```

Would that work for you?

**Comment by rijkvanzanten** [comment]
That seems to do the trick! Is that documented anywhere? :)

**Comment by guillaumelachaud** [comment]
Perfect!

It's only documented indirectly at https://developers.linear.app/docs/sdk/fetching-and-modifying-data#pagination where you can see how the `PaginationOrderBy` enum is being used. Will update the documentation to make it more clear.
