### ISSUE TITLE
Handling OAuth access token expiry: Is it possible to get a refresh token?

### ISSUE THREAD

**Issue by PTaylour** [linear/linear#251]
Hi! 

We're looking to build a Linear OAuth Application. However, I notice that the access token has an `expires_in` field but no mention of a refresh token.

Is it possible to refresh this token without requiring the user's interaction?

**Comment by PTaylour** [comment]
Follow-up question: is `expires_in` in seconds? If so, then I guess we have 10 years to implement token refreshing :D

**Comment by guillaumelachaud** [comment]
Hi!

You are correct. We currently do not provide any `refresh_token`. `expires_in` is in seconds which indeed means the token will expire in 10 years.

We will make sure to give all developers ample notice when we revisit this policy.
