### ISSUE TITLE
Feature request: Time entries for tasks

### ISSUE THREAD

**Issue by DJDANNY123** [linear/linear#254]
Hi Linear Team,

I'm interested in Linear, but one feature that is important for many organisations is relating time on tickets to our organisations timesheets, as customers may want to know exactly how their budget has been allocated/spent, down to the task level. If there was a way to associate time entries with different tasks within Linear(e.g. a new property of a task), these could be fetched using the API to populate a timesheet system, to save developers time populating timesheets in another system while satisfying this organisational requirement.

I'd be interested what you think, whether this goes against some of Linear's founding principles or scope in aiming to build products efficiently, or whether this would be a useful feature that makes sense to you to solve a common problem for organisations and save teams time.

Thanks

**Comment by tommoor** [comment]
This repo is for our public SDKs and API's, not general questions and requests.

If you're still interested in this it's best to contact support or go through our Slack community.
