### ISSUE TITLE
Mutation requesting `__typename` doesn't update the ticket

### ISSUE THREAD

**Issue by tomwyr** [linear/linear#262]
I have a mutation where I update ticket's estimate:
```
mutation($input: IssueUpdateInput!, $issueUpdateId: String!) {
  issueUpdate(input: $input, id: $issueUpdateId) {
    success
  }
}
```
Running it properly updates the ticket, however, adding `__typename` makes the mutation have no effect on the estimate in the Linear app. One thing I've noticed is that the estimation gets updated to the new value if I change the ticket owner.
```
mutation($input: IssueUpdateInput!, $issueUpdateId: String!) {
  __typename
  issueUpdate(input: $input, id: $issueUpdateId) {
    success
  }
}
```
```
{
  "data": {
    "__typename": "Mutation",
    "issueUpdate": {
      "success": true
    }
  }
}
```

**Comment by tomwyr** [comment]
For GraphQL it's both Apollo Studio and a [mobile client in Dart](pub.dev/packages/graphql/).
I should have made it more clear in the first comment perhaps but adding `__typename ` still updates the ticket. The change doesn't get picked up automatically in the Linear web/desktop app.

**Comment by guillaumelachaud** [comment]
I see. Now I can reproduce. That's definitely not an expected behavior. Thanks for reporting!

**Comment by guillaumelachaud** [comment]
I'll close this issue for now. Let us know if you still experience problems!

**Comment by tomwyr** [comment]
Hey @guillaumelachaud I tried running the mutation again and it works flawlessly now. Thanks!
