### ISSUE TITLE
No way to set status of issue using `issueCreate`

### ISSUE THREAD

**Issue by codybreene** [linear/linear#263]
Currently, the `IssueCreateInput ` does not allow for a `status` field, but this is critical when creating an issue, otherwise the issue are automatically set to `backlog`.

**Comment by codybreene** [comment]
Actually, just now seeing: 
<img width="911" alt="image" src="https://user-images.githubusercontent.com/5722230/218540834-26c881d3-3833-4052-bf9d-854e1ee515d0.png">

Still, it's unclear what integers map to which state, so I guess this is more of a request to improve the documentation surrounding stateId (and maybe just adding an enum).

**Comment by guillaumelachaud** [comment]
Hi @codybreene!

You are right: you can set the "status" of an Issue at creation time by passing the proper `stateId` in your `IssueCreateInput` payload.

But the workflow states ids do not map to integers in a predictable way. You probably want to execute a first query to retrieve all the workflow states for a given team with a query like:
```graphql
query WorkflowStates($filter: WorkflowStateFilter) {
  workflowStates(filter: $filter) {
    nodes {
      id,
      name,
      position
    }
  }
}
```
```graphql
"filter": {
  "team": {
    "id": "TEAM UUID"
  }
}
```

This will return you all the possible workflow states for a team: they'll each have a name, an ID, and an integer position. 

Let me know if you have any other question regarding this!

**Comment by codybreene** [comment]
So are `stateIds` different across workspaces? i.e. is there no standard mapping of `todo, in progress, done` etc., to stateIds?

**Comment by codybreene** [comment]
It would be helpful to just have an enum and pass in the string of the status

**Comment by guillaumelachaud** [comment]
> So are `stateIds` different across workspaces? i.e. is there no standard mapping of `todo, in progress, done` etc., to stateIds?

Correct. There is no standard mapping as ultimately these states can be customized by the users.



> It would be helpful to just have an enum and pass in the string of the status

Thanks for the suggestion, I'm filing this internally for consideration.
