### ISSUE TITLE
Couldn't able to `generate access token` in OAuth2.0 authentication

### ISSUE THREAD

**Issue by AppalaNaidu01** [linear/linear#264]
### Can someone please help me with  `generating access token` in OAuth2.0 authentication?
 
 I know the issue I'm facing isn't related here, but I believe someone can help me with the following issue.

I am working on integrating Linear GraphQL APIs into my Flutter project. So, to do that I have chosen `OAuth2.0 authentication` to authorize the Linear APIs.

I followed the documentation mentioned [here](https://developers.linear.app/docs/oauth/authentication).

I am getting an `invalid client` error at `Step-4: Exchange code for an access token` which is to generate the access token.
```
{
    "error": "invalid_client",
    "error_description": "Invalid client: cannot retrieve client credentials"
}
```
I am sure that I am passing the correct parameters in the request as mentioned in the doc.

**Comment by guillaumelachaud** [comment]
Hi @AppalaNaidu01 

Sorry for the late reply! Are you still experiencing any issue here ?

**Comment by bbauman1** [comment]
@AppalaNaidu01 did you figure it out? I'm seeing the same thing

**Comment by AppalaNaidu01** [comment]
Hey @guillaumelachaud, the issue is still there. I was moved away from the OAuth task, but I can help to figure it out.

**Comment by arjunpredev** [comment]
I'm still facing this issue.
