### ISSUE TITLE
Suddenly got errors while querying projects

### ISSUE THREAD

**Issue by flex-tackgyu** [linear/linear#267]
We were using @linear/sdk 1.22.0 before and suddenly got the following error:

```
Cannot query field "milestone" on type "Project".
```

Bumped to version 2.1.0 and the error changed such as:

```
Cannot query field "initiative" on type "Project".
```

It seems graphql schemas broken somehow.
Can you guys check this out?

**Comment by guillaumelachaud** [comment]
Hi @flex-tackgyu!

We have released a breaking change on the API. The SDK needs updating and will be very soon. I'll report back as soon as it's available.

**Comment by guillaumelachaud** [comment]
SDK version `2.2.0` has been released with a fix for this. Let me know if you still experience issues.

**Comment by guillaumelachaud** [comment]
@superlight-bec There has been more updates on our end. If you still encounter the issue with the latest version of the SDK, would you mind sharing a sample of what you're doing to reproduce the issue?

Thanks!

**Comment by guillaumelachaud** [comment]
@superlight-bec I'm going to close this one. Let me know if you still need help here.
