### ISSUE TITLE
Import closed issues from Github

### ISSUE THREAD

**Issue by antimius** [linear/linear#281]
The desktop/web app offers the option to import already closed issues from Github. The CLI importer seems to be missing this functionality.

**Comment by guillaumelachaud** [comment]
Hi @antimius!

You are correct. The CLI importer doesn't support as much as the desktop one. Is there any reason you need to resort to the CLI importer?

**Comment by antimius** [comment]
Hi @guillaumelachaud, the reason I was using the CLI was because the desktop always gives me an error:

```Unable to find repo myusername/myprivaterepo. Did you select `repo` scope for your GitHub token?```

Of course, Linear creates it's own "Linear Importer" oauth app in GitHub, so I have no idea why the desktop app doesn't work for me.

**Comment by guillaumelachaud** [comment]
Hi @antimius 👋 

Sorry to hear about the trouble. We recently shipped a fix regarding the Github integration for personal accounts. Are you still experiencing issues with the in-app importer ?
