### ISSUE TITLE
Github integration not tracking through board workflow

### ISSUE THREAD

**Issue by francisleigh** [linear/linear#286]
Hello 😊, 

I recently integrated Linear with my GitHub and I found that when pushing up a branch to my repo with the branch name provided by a Linear ticket, it wouldn't move my ticket into `In Progress` ...

At my workplace, I've integrated Linear with GitLab and the above issue doesn't exist, when I create a branch and push, the ticket moves into "In Progress"

When raising a PR in GitHub, the ticket links up absolutely fine, albeit - no progress through the board but I can see the PR in the ticket itself.

Is this a limitation of the GitHub integration? or am I doing something goofy?

*P.S.* I also disconnected and reconnected my GitHub account but still no 🎲.

**Comment by guillaumelachaud** [comment]
Hi @francisleigh 👋 

I encourage you to reach out to either the Slack [community](https://linear.app/join-slack) or the support through the app. We'll be better equipped there to investigate what's going wrong with your integration!

Thanks!
