### ISSUE TITLE
Can't connect issue, created on "My issues"-page, to completed project

### ISSUE THREAD

**Issue by Rvervuurt** [linear/linear#287]
I recently started using Linear, and created an issue on the "My issues"-page. Afterwards, I made a project, which I marked as "Completed", since that project got delivered a while ago.

However, the issue I created, is a new issue for the finished project, but I can't connect that issue to the project, unless I change the project's status to anything else than "Completed".

If I go into the project and create a new issue there and assign myself, it works perfectly fine: the issue shows up on my "My issues"-page, and the project is still set as "Completed".

If I change the project's status to "In progress", go to "My issues", connect the issue to the project, and after that is done, change the project's status to "Completed" again, the issue is still connected and still has the "In progress" status.

So my question is basically: How do I connect an issue to an existing, completed project, without re-opening the project and without recreating the issue on said project?

**Comment by guillaumelachaud** [comment]
@Rvervuurt 

I tested this and can add an issue to a completed project without having to re-open it first.

Ultimately, It looks like your question regards how to use product, it's not specific to the SDK or importer. You should ask your question either in the Slack [community](https://linear.app/join-slack) or reach out to support through the app. You'll find more assistance on how to resolve your issue there.

Thanks!
