### ISSUE TITLE
Bug report: "Snooze" and "Remind me" share the same keyboard shortcut

### ISSUE THREAD

**Issue by CharlesMangwa** [linear/linear#297]
hey! 👋 

my team and i recently moved to linear from jira so i have to start by saying: thank you! you've built a pretty fantastic tool, keep up the amazing work! 🙌 

i've just encounter a pretty sneaky bug that i'm assuming affects all platforms: the **`Snooze issue until...`** and **`Remind me about this issue...`** actions share the exact same keyboard shortcut: **`H`** (and the snooze command is the one that prevails in the end btw).

<img width="764" alt="Screenshot 2023-03-17 at 11 48 35" src="https://user-images.githubusercontent.com/8975443/225884215-c01dec22-3294-4a90-bd0e-5632771e9adb.png">
<img width="763" alt="Screenshot 2023-03-17 at 11 47 55" src="https://user-images.githubusercontent.com/8975443/225884029-3293a97e-71eb-4274-978b-ceccb5f79227.png">

**Comment by pacocoursey** [comment]
Thanks! We've updated the shortcut for Snooze to be <kbd>⇧</kbd> <kbd>H</kbd>. It'll be in the next changelog.
