### ISSUE TITLE
Plans to filter webhook by issue?

### ISSUE THREAD

**Issue by PTaylour** [linear/linear#298]
Hi!

I notice you now support [WebhookCreateInput.teamId](https://studio.apollographql.com/public/Linear-API/schema/reference/inputs/WebhookCreateInput?variant=current#teamId). Do you have any plans to support `issueId` (and/or other resource ids) as an input filter?

My use case involves subscribing to changes to only a small percentage of issues within a team. If we are to support multiple teams across multiple organizations, then we'll have to deal with quite a lot unnecessary load.

Cheers!

**Comment by guillaumelachaud** [comment]
Hi @PTaylour!

It's not on the roadmap yet but I've filed an issue internally to keep track of it!

Thanks!
