### ISSUE TITLE
How this amazing gradient effect works ?

### ISSUE THREAD

**Issue by meerns** [linear/linear#304]
Hello there, I know this is a bit out of context but I was exploring a linear website and I came across this beautiful animation in the scroll (the glowy light gradient), I spend almost an hour using the dev tool I could not get how it works, so I'm curious how it's done and any help will be appreciated

**Comment by pacocoursey** [comment]
Hi @meerns, your question is a little unclear but I believe you're referring to the hover effects on https://linear.app/features. Hyperplexed put together a video describing how to achieve this effect with CSS/JS: https://www.youtube.com/watch?v=htGfnF1zN4g

**Comment by meerns** [comment]
> Hi @meerns, your question is a little unclear but I believe you're referring to the hover effects on https://linear.app/features. Hyperplexed put together a video describing how to achieve this effect with CSS/JS: https://www.youtube.com/watch?v=htGfnF1zN4g

Thanks for the reply, @pacocoursey
