### ISSUE TITLE
Add Issue Number and URL to Web-hook's Payload.

### ISSUE THREAD

**Issue by sbansal1999** [linear/linear#314]
We were building a Zulip Integration for Linear but were facing problems when trying to thread `Comment` and `Sub-Issue` with their parent events. 

Adding the following fields will help in threading in a better way:

- [ ] `Issue_Number` and `Issue_URL` to the Comment event webhook.
- [ ] `Parent_Issue_Number` to the Sub-Issue event webhook.

**Comment by tommoor** [comment]
Hi @sbansal1999 – sorry this was missed, this repo is not for general feature requests but tracks issues in the SDK. If you still need these features I'd encourage reaching out to support directly
