### ISSUE TITLE
Improvement request: Automatically start project when issue is "In progress"

### ISSUE THREAD

**Issue by guillego** [linear/linear#334]
First things first: Thanks for building such an amazing product. It's software that gives a lot of joy to use!!

I have this issue, and I'm not sure if it should be reported here or somewhere else but I was wondering if it would be possible for project to be set to "In progress" automatically when the issues that are part of the project are moved to in progress. I was puzzled just now trying to find a project in the "Active projects" view, only to find out that it was in the "Backlog" because it hadn't been manually set to "In progress".

Thanks!

**Comment by mo9a7i** [comment]
I would like to extend my thanks as well to the team. I recently migrated from another tool and my team, within a week time was able to function and enjoy the tool.

In addition to the above, it can be auto started or marked done based on internal issues. Also, The start date and end date if not set can adopt the internal issues first issue start date and last issue end date. when more issues are added that are either beyond or before the project dates, an alert will pop up to notify the user that project dates should be updated or issue dates re-aligned.

**Comment by tommoor** [comment]
This repo is for our public SDKs and API's, not general questions and requests.

If you're still interested in this it's best to contact support or go through our Slack community.
