### ISSUE TITLE
improvement request: make Project/startDate public

### ISSUE THREAD

**Issue by thewisenerd** [linear/linear#335]
why is Project/startDate ([docs](https://studio.apollographql.com/public/Linear-API/variant/current/schema/reference/objects/Project#startDate)), which is a user-settable property on a project, specified as an internal property?

I am currently work-around-ing this by using a `rawRequest`, but this should not be necessary, IMO.

`targetDate` is public..

```javascript
    let startDateResponse = await linear.client.rawRequest(`query ($projectId: String!) { 
        project(id: $projectId) {
            startDate
        }
     }`, {
        projectId: project.id,
    });
```

**Comment by guillaumelachaud** [comment]
Hi @thewisenerd 

We have fixed this and the project's start date is now public. It's available in the API and in the SDK `7.0.0` thaht just got released.

Please let me know if you still have some issues with this field.
