### ISSUE TITLE
Commenter is subscribed when `doNotSubscribeToIssue` is true

### ISSUE THREAD

**Issue by mok0230** [linear/linear#366]
Hi,

I am making a call to the Linear API like:

```
this.client.createComment({ doNotSubscribeToIssue: true, issueId: issue.id, bodyData });
```

And the commenter still subscribes to the issue. Is this a bug or am I misunderstanding what this flag is meant to do?

**Comment by guillaumelachaud** [comment]
Hi!

Thanks for the report, this is a bug. Commenter shouldn't be subscribed to the issue when passing flag `doNotSubscribeToIssue`. Looking into it.

**Comment by guillaumelachaud** [comment]
@mok0230 This should be fixed now. Let me know if you still encounter the issue.
