### ISSUE TITLE
request: Mermaid support

### ISSUE THREAD

**Issue by smedegaard** [linear/linear#380]
## Request

It would be _very_  helpful if the markdown editor would support [Mermaid](https://mermaid.js.org/) syntax to include diagrams directly in the text (just like Github does).

## Example
```
```mermaid
flowchart LR
     Node1 <--> Node2
    Node2 --> Node3
    Node3 --> Node1
```

Becomes
```mermaid
flowchart LR
    Node1 <--> Node2
    Node2 --> Node3
    Node3 --> Node1
```

**Comment by romanr** [comment]
What is Linear's position about embedding charts and rich editing in issues? There's no integration that does that, and only this ticket that is ignored. 

I think this whole Github issue tracker is bogus and nobody watches it. They have real issues in Linear.app itself.

**Comment by tommoor** [comment]
Hi folks, this repo is for our public SDKs and API's, not general questions and requests.

For Linear feature requests it's best to contact support or go through our Slack community.
