### ISSUE TITLE
Metadata object is always empty when retrieving links

### ISSUE THREAD

**Issue by philippeauriach** [linear/linear#427]
Hello,

we created an internal integration to manage links to deployment urls. We want to identify them using the metadata field on "attachments" by adding an id. This field is correctly filled and I can see them when testing with https://studio.apollographql.com/public/Linear-API/variant/current/explorer, but I cant get them using the linear-sdk. 

I tried all the following : 
```
const attachments = await issue.attachments()
const attachment = await linearClient.attachment(id)
```
And everytime I get an empty `medata: {}` property on the result. Is there a way to ask for this property to be in the response ?

thanks

**Comment by guillaumelachaud** [comment]
Hi @philippeauriach 👋 !

Thanks for the report. This got fixed and released with the latest version of the SDK. Let me know if you still experience any issues there.

**Comment by philippeauriach** [comment]
Hi @guillaumelachaud! Thank you, it is working now!
