### ISSUE TITLE
Duplication warning when creating nested label that exists in another nested context

### ISSUE THREAD

**Issue by miraroot** [linear/linear#428]
Couldn't find where to report bugs other than here, please point me to the correct location if there's a better place to do so :)

* when creating a nested label (e.g. Project A/Milestone 1) and there's already another label called Milestone 1 in another nested context (e.g. Project B/Milestone 1), I get an error (see below and am unable to create the label)

![Screenshot 2023-12-11 at 12 16 25](https://uploads.linear.app/6ee3ee0f-1ea6-4b88-a969-f63432eeb657/aa3c034d-55f9-4c79-8c30-cb3f0d14c8dc/b65fcfe9-67ec-46ef-82ae-63c6a1e85009?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZlZTNlZTBmLTFlYTYtNGI4OC1hOTY5LWY2MzQzMmVlYjY1Ny9hYTNjMDM0ZC01NWY5LTRjNzktOGMzMC1jYjNmMGQxNGM4ZGMvYjY1ZmNmZTktNjdlYy00NmVmLTgyYWUtNjNjNmExZTg1MDA5IiwiaWF0IjoxNzAyMjkzNTgxLCJleHAiOjMzMjcyODUzNTgxfQ.Zv84TmENLeSofKPIeYvuOlZMwqRHNUfHIfgyRAw8CVI "=432x")

**Comment by pauldijou** [comment]
@miraroot Currently, all labels must have different names, it does not matter if they are nested inside a label group. I understand how this could be a limitation for your use-case. I will raise it to the team and keep you updated.

In the meantime, if that helps, Projects have the concept of milestones built-in directly. You can see them in the side panel of the project.

![image](https://github.com/linear/linear/assets/1275293/6b1e5a9b-5c27-4fa1-b3e7-43d75a3d3a62)

You can report problems directly inside the app with the Help button on the bottom-left of the page with "Send feedback".

![image](https://github.com/linear/linear/assets/1275293/d22e20ef-f22e-4659-9c54-3e25621ab539)
