### ISSUE TITLE
"global" is not defined

### ISSUE THREAD

**Issue by eschirtz** [linear/linear#430]
Brand new vue3 project using vite, typescript and eslint via `npm create vue@latest` [docs](https://vuejs.org/guide/quick-start)

Using the sample code in the root component of sample vue3 app, I get the following error.
![CleanShot 2023-12-16 at 21 47 45@2x](https://github.com/linear/linear/assets/24927782/c9cc7d01-94c2-4df2-a229-8c77f766347c)

Relevant client code: 
```ts
// App.vue in <script lang="ts"> tag
import { RouterLink, RouterView } from 'vue-router'
import HelloWorld from './components/HelloWorld.vue'
import { LinearClient, User } from "@linear/sdk";
import type { LinearFetch } from "@linear/sdk";

const linearClient = new LinearClient({ apiKey: "MY_KEY" });

async function getCurrentUser(): LinearFetch<User> {
  return linearClient.viewer;
}

console.log(await getCurrentUser());

```

Error line in minified sdk:
![CleanShot 2023-12-16 at 21 47 37@2x](https://github.com/linear/linear/assets/24927782/9f983691-5732-4e2e-8c42-26efa8388be0)

Poked at it for a bit with no luck. Let me know if I can provide any more info! I'd love to be able to use the sdk client-side while prototyping. I've got it working in a pure node.js environment.

**Comment by leelasn** [comment]
Hi there, our SDK is only meant to be server-side and not in a client app directly

**Comment by jasonbarry** [comment]
On https://linear.app/developers/sdk it says 

> It’s written in Typescript but can also be used in any Javascript environment.

which I would assume to mean that it can run in browsers.
