### ISSUE TITLE
[Feature request] Project’s label

### ISSUE THREAD

**Issue by ftognetto** [linear/linear#438]
Hello It would be awesome to retrieve all the labels used in a single project from the Sdk or graphql. 
I see that on linear is possible going on the project then on the right sidebar select “labels” it shows all the labels used in that project.
Thank you!!!

**Comment by rlargman** [comment]
You can fetch this information using a query like so:

```
query Project($projectId: String!, $cursor: String) {
  project(id: $projectId) {
    issues(first: 10, after: $cursor) {
      edges {
        cursor
        node {
          labelIds
        }
      }
    }
  }
}
```

Hope that helps!
