### ISSUE TITLE
Support for opening links from slack directly into desktop app?

### ISSUE THREAD

**Issue by thedmeyer** [linear/linear#44]
Is there a way to make it so linear issue links from slack open directly into the desktop app?

I'm aware of `Cmd Ctrl ,` but is there a more direct option for the slack integration?

Like URIs such as `linear://{workspace}/*`

**Comment by rlargman** [comment]
We do not currently have universal links, but it is on the roadmap. Until then, you can use a solution like [Choosy](https://www.choosyosx.com/). I would recommend joining our [Slack community](http://linear.app/join-slack) to get faster answers to your questions, or to search through previous answers that might help you as well!

**Comment by ericbf** [comment]
Is it still the case that there is no universal link? My system shows that the desktop app registered the `linear:` URL, and the browser is able to open issues in the desktop app. Also the [changelog from Nov 18, 2021](https://linear.app/changelog/2021-11-18-front-integration-and-universal-links) talks about universal links. What’s the schema to open up to a specific issue?

--------

Seem to have it figured out. The url seems to follow the schema `linear://${team}/issue/${issue-id}`

**Comment by CoreyCole** [comment]
any ideas for how to do this with finicky? it is open source choosy. this is what I tried:
```javascript
// ~/.finicky.js
export default {
  defaultBrowser: "Zen Browser",
  rewrite: [
    {
      // Open Linear links in the native app
      match: "https://linear.app/*",
      url: (url) => {
        // Convert https://linear.app/... to linear://linear.app/...
        return url.toString().replace("https://", "linear://");
        // also tried 
        // return url.toString().replace("https://", "file://linear://");
      },
    },
  ],
  handlers: [

  ],
};
```

**Comment by ericbf** [comment]
> any ideas for how to do this with finicky?

I got it working with finicky with something like this:

`~/.finicky.ts`:
```
import type { FinickyConfig } from "/Applications/Finicky.app/Contents/Resources/finicky.d.ts"

export default {
	defaultBrowser: "Safari",
	rewrite: [
		{
			// Open linear tickets in app
			match: "https://linear.app/*",
			url: (url) => {
				// It's something like https://linear.app/{team}/issue/{id}/{name}
				const match = url.pathname.match(/([^/]+)\/issue\/([^/]+)/)

				if (!match) {
					// We couldn't extract the team and ID.
					return url
				}

				const [, team, id] = match

				return `linear://${team}/issue/${id}`
			}
		}
	],
	handlers: [
		{
			match: "linear://*",
			browser: "/Applications/Linear.app"
		}
	]
} satisfies FinickyConfig
```
