### ISSUE TITLE
[Feature request] Enhanced Ticket Types and Custom Fields

### ISSUE THREAD

**Issue by carlroeber98** [linear/linear#440]
Hi Linear Team,

Love your application! I have a feature request to enhance the ticket management and further elevate the functionality of the platform. Currently, we manage different types of tickets such as bugs, epics, discussion tasks, and spikes by incorporating prefixes in the ticket titles. However, I envision a more streamlined and efficient approach by introducing dedicated ticket types similar to those available in Jira. Additionally, customizing fields per type, such as a timebox field for spikes instead of the estimate, would add flexibility.

Thanks for considering this improvement!

**Comment by mayacoda** [comment]
Hi @carlroeber98, thanks for your feedback!

Would [label groups](https://linear.app/docs/labels#label-groups) help solve your use case for ticket types?

**Comment by carlroeber98** [comment]
Hey @mayacoda, 

unfortunately, the label groups are not really helpful for us. We currently use labels to identify which project/repo the issue relates to, for example the backend or a specific frontend application. 
I don't want to have multiple topics (issue type & project reference) for the labels, and I think the issue type as a new field on issues could be quite a nice solution to that.

**Comment by mayacoda** [comment]
Got it, thanks for clarifying. Custom properties on issues are under consideration as a future improvement. I've added your feedback to our discovery.
