### ISSUE TITLE
Feature Request: Link Github discussions

### ISSUE THREAD

**Issue by timkelty** [linear/linear#446]
We often end up making actual Linear issues from Feature Requests that come in as Github discussions.

It doesn't appear Linear's Github integration deals with this at all.

It would be great if:

* we had the option to include discussions in our incoming Triage
* Discussion status was synced with the Linear issue being completed

![CleanShot 2024-02-10 at 08 42 59@2x](https://uploads.linear.app/6ee3ee0f-1ea6-4b88-a969-f63432eeb657/805284d2-b51a-4bf3-90d3-162ca58569fc/70ddd8fc-4c66-447c-a690-ce4f79c655d3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZlZTNlZTBmLTFlYTYtNGI4OC1hOTY5LWY2MzQzMmVlYjY1Ny84MDUyODRkMi1iNTFhLTRiZjMtOTBkMy0xNjJjYTU4NTY5ZmMvNzBkZGQ4ZmMtNGM2Ni00NDdjLWE2OTAtY2U0Zjc5YzY1NWQzIiwiaWF0IjoxNzA3NTc4NjM2LCJleHAiOjMzMjc4MTM4NjM2fQ.\_JUX1HvJHKmh3tAu5-Oy5CbT5nm3sM4OcDxTCt6QGUk)

**Comment by timkelty** [comment]
> [LIN-18696 Feature Request: Link Github discussions](https://linear.app/linear/issue/LIN-18696/feature-request-link-github-discussions)
Hey, thats what I want!

**Comment by tommoor** [comment]
There are no plans to include entities other than Issues right now I'm afraid – cancelling this out as we don't really use this repo for feature requests. But we'll keep track of this and consider as a future addition.
