### ISSUE TITLE
[Feature Request] Can the GitHub/GitLab branch-based workflow automation also support a release based workflow?

### ISSUE THREAD

**Issue by mathiasose** [linear/linear#448]
The recently released feature in https://linear.app/changelog/2024-02-01-project-update-comments#branch-specific-workflow-automations looks great for `gitflow`-based projects.

It doesn't look like it fits quite with the `github-flow`-ish workflow we use though, where you merge PRs to main to put them in _staging_ and you create tags+releases to deploy to _production_. Since that last step isn't a _branch_ it's unclear from the docs if it's supported. It _feels_ to me like it should be possible to create a regex pattern for release names just like you can with branch names, but I don't know the details of how you've implemented this.

Is this something you support but haven't documented, or something you can look into supporting in a future release?

## Related issues
- https://github.com/linear/linear/issues/325

**Comment by mufeez-amjad** [comment]
Hi @mathiasose, we plan on addressing your use-case in the near future when we incorporate functionality to track/manage releases in Linear. Until then, you could make a custom GitHub action that responds to added tags, here's an example from the community: https://github.com/rayonapp/linear-sync.
