### ISSUE TITLE
`linearClient.teams` is failing as of 2023-03-04

### ISSUE THREAD

**Issue by jazeee** [linear/linear#464]
When running code like:
```
 await linearClient.teams({ filter: {
    key: {
      eq: key,
    },
  }})
```

We get an error like:
```
Cannot query field "issueSortOrderDefaultToBottom" on type "Team"

...
"errors":[{"message":"Cannot query field \"issueSortOrderDefaultToBottom\" on type \"Team\".","locations":[{"line":108,"column":3}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","type":"graphql error","userError":true,"meta":{}}}],"status":400,"headers":{}},"request":...
```

graphql schema appears to have changed, and broke this package.

**Comment by guillaumelachaud** [comment]
Hi @jazeee 

We have updated the SDK to build against the latest schema. Can you try with `16.0.0` ?

**Comment by guillaumelachaud** [comment]
Additionally, we have added back `issueSortOrderDefaultToBottom` field, as a deprecated field. This should fix the problem without requiring you to update to the latest version of the SDK.

Please let us know if you still encounter any issues.

**Comment by jazeee** [comment]
Confirmed. That works.

**Comment by jazeee** [comment]
Hmm, so the next issue is:
```
linearClient.createIssue({ teamId: team.id, title, description, assigneeId: linearViewer.id });
```
doesn't create a ticket. Instead it returns an old ticket from linear.app. (the `issue.url` is a several month old ticket)

I'll spawn a new issue.

**Comment by jazeee** [comment]
https://github.com/linear/linear/issues/466
