### ISSUE TITLE
`issueSortOrderDefaultToBottomfield` Breaking change in API broke the SDK

### ISSUE THREAD

**Issue by philippeauriach** [linear/linear#465]
Hello 👋🏻
Since a few hours, the breaking change in the API (see https://studio.apollographql.com/public/Linear-API/variant/current/changelog removing `issueSortOrderDefaultToBottomfield`) broke our integrations, even if we don't actually query this field, we get the error 
```
message: 'Cannot query field "issueSortOrderDefaultToBottom" on type "Team".'
```
When running 
```
const team = await issue.team;
```
(we do not pass specific options such as `issueSortOrderDefaultToBottomfield`)

It seems that the SDK is waiting for a release on this pull request: https://github.com/linear/linear/pull/461, maybe it will fix our issue?

Anything we could do to help this release ?

**Comment by guillaumelachaud** [comment]
Additionally, we have added back `issueSortOrderDefaultToBottom` field, as a deprecated field. This should fix the problem without requiring you to update to the latest version of the SDK.

Please let us know if you still encounter any issues.
