### ISSUE TITLE
When running `linearClient.createIssue`, the API responds with an old ticket, and doesn't create a ticket

### ISSUE THREAD

**Issue by jazeee** [linear/linear#466]
When I run `linearClient.createIssue` for a team having 671 tickets, Linear doesn't create a ticket.
Instead, it returns a 2 month old ticket (even if the title and description is unique).

```
linearClient.createIssue({ teamId: team.id, title, description, assigneeId: linearViewer.id });
```
the `issue.url` is a several month old ticket...

**Comment by jazeee** [comment]
Here is my repo, if you want to take a look. I can also work with tech support (we have a paid account).
https://github.com/jazeee/linear-creator

**Comment by guillaumelachaud** [comment]
Thanks for the link to the repo. At first glance, your implementation looks correct to me. I cannot reproduce your issue though. If you don't mind reaching out to support, we can follow-up there and, with more details about your account, look into logs to see what might be going on.

**Comment by jazeee** [comment]
Ok, testing further, when I revert back to `"@linear/sdk": "13.0.0"`, then I can create tickets without issue.
I then reinstalled 15.0.1 and had no issue, and then re-tested with 16.0.0, and had no issue.

Somehow this is resolved...
