### ISSUE TITLE
Feature Request: Ability to choose which github repo the new Linear issue will be synced to

### ISSUE THREAD

**Issue by CMCDragonkai** [linear/linear#469]
Right now it appears you have to select a default github repository to sync your new linear issue to.

If we have lots of repos, it would make more sense to be able to select which github repository we want to sync it to.

**Comment by tommoor** [comment]
Hi @CMCDragonkai thanks for the feedback, we'll consider this for a future improvement. Closing this issue as this repo is for issues with the SDK.
