### ISSUE TITLE
Time estimate within Linear?

### ISSUE THREAD

**Issue by rambalachandran** [linear/linear#470]
Hi, is there any roadmap to include time estimate vs actual spend for issues within Linear? I like to estimate time vs actual spend on issues and the integrations that are available is not good.

**Comment by smcgivern** [comment]
While we don't have inbuilt time tracking, or any immediate plans to add it, we do provide data through the API which contains information of when an issue status has changed. You could in theory use this data to calculate how long each issue stays in each status. You would need to maintain your own data pipeline to achieve this so you'll be the best judge as to whether this is an option for you. 
​﻿

You can also access this information using our Airbyte integration and then syncing this into any data store you are using. Time spent in status as an insight is in our backlog of feature requests to add to the insights features Insights and the Airbyte integration is only available on our Plus plan though.
