### ISSUE TITLE
CLI importer fails to authenticate

### ISSUE THREAD

**Issue by guillaumekh** [linear/linear#471]
### Description

CLI importer fails to authenticate w/ Linear API when invoked w/ personal API key

### Context

Broadcom/VMware/Pivotal have [removed all non-entreprise pricing tiers for Pivotal Tracker with a 56 days notice](https://news.ycombinator.com/item?id=39607630), which should force whatever users they still had left to flee to other solutions (e.g. Linear).

### Steps to reproduce

```sh
cat << EOF | tee test.csv
Id,Title,Labels,Iteration,Iteration Start,Iteration End,Type,Estimate,Priority,Current State,Created at,Accepted at,Deadline,Requested By,Description,URL,Owned By,Owned By,Blocker,Blocker Status,Comment,Comment,Task,Task Status,Task,Task Status,Task,Task Status,Task,Task Status,Task,Task Status
131983759,LAN API: GET /nowplaying should return track artwork,"",1,"Oct 24, 2016","Oct 30, 2016",feature,0,p3 - Low,accepted,"Oct 10, 2016","Oct 25, 2016",,Guillaume Khayat,"per zone",https://www.pivotaltracker.com/story/show/131983759,,,,,,,,,,,,,,,,
EOF
npm i @linear/import
npx linear-import
# input personal API key
# select Pivotal
# select test.csv file
```

### Expected result

CSV gets imported in Linear

### Actual results

HTTP400 error (Authentication required, not authenticated error)

### Versions used

@linear/import: 1.9.9
node: v20.11.0

**Comment by guillaumekh** [comment]
Mmh.

I've generated & tried 3 different Personal API keys. I copy-paste them straight from the linear web app.

Here is my latest attempt (key is revoked too):
<img width="875" alt="image" src="https://github.com/linear/linear/assets/1011994/40612995-fad3-4712-99fa-2af3084f84c6">

I'm admin of our workspace.

Anything I should do to get a better understanding of what's going on?

**Comment by guillaumekh** [comment]
Ah well it works now.

The only thing I changed was I deleted all cache (indexedDB, cookies, etc) from my browser and regenerated a new personal key.

I don't understand what could have happened.

I'll close the ticket if the issue does not come back.

**Comment by tarngerine** [comment]
thanks, we will investigate the logs and see if we can come up with a more concrete answer here

**Comment by tarngerine** [comment]
also please make sure you revoke the key above (i'm sure you did, but due diligence…)
