### ISSUE TITLE
[Feature Request]: .pkg and .msi bundles

### ISSUE THREAD

**Issue by tance77** [linear/linear#501]
Is it possible to get a `.pkg` and `.msi` bundles for Linear? I would love to add Linear to our deployment bundle but need one of these types of installers to do it automatically.

**Comment by tommoor** [comment]
Hi @tance77 which platform do you use for distributing installers?

**Comment by tance77** [comment]
@tommoor 

https://www.apple.com/business/essentials/

**Comment by tommoor** [comment]
I don't know about apples system, is it not possible to use a DMG? This is Apple's format after all

**Comment by tance77** [comment]
@tommoor unfortunately know it requires a `.pkg` or for Linear to be on the app store. I was really hoping it would be super easy to output a .pkg in the build step.

**Comment by tommoor** [comment]
Sorry do you have a screenshot or something of the configuration? Appreciated

**Comment by tance77** [comment]
@tommoor here is  a screenshot of the custom `pkg` configuration. 
![Screenshot 2024-03-21 at 11 21 33 AM](https://github.com/linear/linear/assets/3421501/400c8a81-765d-49c6-81c8-d30c5fa8364c)

I tried to make my own from the app but it's not signed when i do it this way so apple rejects it. Would love to see one from Linear :)

**Comment by tommoor** [comment]
We use a third-party build tool, so I'm petitioning them to add support for pkg but I wouldn't expect this to be changed in the near term unfortunately.

**Comment by tance77** [comment]
@tommoor thanks! Much appreciated! We really love your app!
