### ISSUE TITLE
Feature Request: Customizable Priority Levels

### ISSUE THREAD

**Issue by lukasab** [linear/linear#514]
## Overview
Our team extensively uses Linear for managing our projects, and it's been a crucial tool in our workflow. However, we've identified a limitation in the current priority system that impacts our efficiency and task management process.

## Current Challenge
Linear's existing priority settings include four levels: Urgent, High, Medium, and Low. Our project management approach requires a more nuanced priority system, specifically six levels (P1 to P6), to accurately reflect the urgency and importance of tasks.

To circumvent this, we created a label group to represent these additional priorities. However, this workaround prevents us from leveraging Linear's sorting feature by priority, which is great for efficiently managing our task backlog.

## Feature Request: Customizable Priority Levels
We propose the introduction of customizable priority levels to better support diverse workflows and enhance project management flexibility. This feature would ideally allow users to:

- **Define Custom Priority Levels:** Enable users to create a tailored set of priorities (e.g., P1 to P6), offering more precision in task urgency and importance.
- **Order Priorities:** Allow users to arrange these custom levels in a specific sequence to reflect their relative importance accurately.
- **Add Descriptions:** Provide the option to include descriptions for each priority level, offering additional context and guidance on their application.

## Conclusion
Implementing customizable priority levels would significantly improve task management efficiency and flexibility, particularly for teams with complex workflows. It would also restore the ability to sort issues by priority. We appreciate your consideration of this feature request

Thank you for your time and attention :)

**Comment by tommoor** [comment]
Hi @lukasab this repository is for our CLI and associated bugs and requests, for general product feature requests you're welcome to email into support@linear.app
