### ISSUE TITLE
Feature Request: Display sub-issues differently, differentiate from parent issues by color, icon, or style

### ISSUE THREAD

**Issue by AVGVSTVS96** [linear/linear#516]
At a glance, it's hard to tell which issues are sub issues and which are parents. While the labeling makes it clear upon further inspection, I was thinking that it would be nice to add something else to differentiate sub issues from parent issues, like a different background color, or an icon. This would be a nice addition for both the list and board view.

**Comment by tarngerine** [comment]
ah, not sure why GH marked it as not planned. there is an existing feature request we're tracking in our Linear instance that i've merged this into as a duplicate. thanks for filing this request
