### ISSUE TITLE
Feature Request: Tagging teams

### ISSUE THREAD

**Issue by Datarogie** [linear/linear#522]
It would be highly beneficial to have the capability to tag entire teams rather than just individuals, particularly in comments. This feature would help prevent the formation of work silos that often occur when collaborating with the same individual repeatedly. It ensures more inclusive communication and distributes queries or tasks more evenly among team members.

**Comment by tommoor** [comment]
Thanks for the request, we'll attach this to the internal issue. As this repo is for issues related to the CLI I'm going to close this issue to keep it clean.
