### ISSUE TITLE
Import to Linear

### ISSUE THREAD

**Issue by ayoubrabeh** [linear/linear#537]
Hello,
I was trying to import the export i made from linear, but i had an error that stops the import:

![Capture d'écran 2024-05-27 141000](https://uploads.linear.app/6ee3ee0f-1ea6-4b88-a969-f63432eeb657/282ae16b-3ccb-4697-be63-13ad96f30e90/c235d670-3960-4ded-8b4f-1da6acefa641?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZlZTNlZTBmLTFlYTYtNGI4OC1hOTY5LWY2MzQzMmVlYjY1Ny8yODJhZTE2Yi0zY2NiLTQ2OTctYmU2My0xM2FkOTZmMzBlOTAvYzIzNWQ2NzAtMzk2MC00ZGVkLThiNGYtMWRhNmFjZWZhNjQxIiwiaWF0IjoxNzE2ODExOTE4LCJleHAiOjMzMjg3MzcxOTE4fQ.\_r4Cz-qnRvMb0xJOBtv1WHrMIFyE_r815cMA01DDVEA)

![image](https://uploads.linear.app/6ee3ee0f-1ea6-4b88-a969-f63432eeb657/05fbefd3-c0fe-40e5-819f-e678fe7d8e6e/4ea19767-7af6-4810-9ff2-6ad62ea2db42?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZlZTNlZTBmLTFlYTYtNGI4OC1hOTY5LWY2MzQzMmVlYjY1Ny8wNWZiZWZkMy1jMGZlLTQwZTUtODE5Zi1lNjc4ZmU3ZDhlNmUvNGVhMTk3NjctN2FmNi00ODEwLTlmZjItNmFkNjJlYTJkYjQyIiwiaWF0IjoxNzE2ODE0Njk1LCJleHAiOjMzMjg3Mzc0Njk1fQ.dRdY7ujOcNrp3QPSoC5_FuIoGehge8VyiBrNYrHU7Tw)

**Comment by tommoor** [comment]
Hey, could you let us know the exact commands you use? Thanks

**Comment by ayoubrabeh** [comment]
Running the import through the CLI with linear-import command.

**Comment by tommoor** [comment]
If it helps we believe this is related to todos/checkboxes in the issue description

**Comment by mikeeggertsen** [comment]
I think it happens when the description starts with a todo/checkbox, then for some reason linear adds a ```'``` in front of the line, which breaks the importer. 

So I resolved it by importing the csv in Google sheets and manually removing all the ```'``` and then exporting as csv and running the cli again.

Hope this helps!

**Comment by smcgivern** [comment]
Thanks, I was able to reproduce with that hint.

There are a few things going on here:

1. An API bug in our todo list parsing.
2. The CSV export (reasonably) adds a leading `'` to fields that start with `-`, to prevent any spreadsheets from trying to parse it as a number.
3. The CSV import code doesn't strip leading `'`s in this case.

**Comment by smcgivern** [comment]
I've fixed 1 and 3 (https://github.com/linear/linear/pull/540) now - no need to fix 2, that's working as intended.

@ayoubrabeh could you try again please with the latest version of the importer? https://github.com/linear/linear/releases/tag/%40linear%2Fimport%401.14.0

**Comment by smcgivern** [comment]
Thanks. That looks like a broken reference to an uploaded image. Does the image display correctly in Linear in the source workspace?

**Comment by ayoubrabeh** [comment]
Yes the link works fine, i replace it with /link for img in my comment to avoid public access to the img

**Comment by tommoor** [comment]
I guess the link works fine in the originating workspace, but in the workspace you're importing into it does not have authentication to access that url.

**Comment by smcgivern** [comment]
Yes, it looks like for new uploads to issues, we include the `signature` param in the URL so it will always work, even without cookies, but that doesn't apply to this image for some reason.

If you remove the image from the issue description and re-add it, does this work?

**Comment by tommoor** [comment]
Could you share the link in question? It's inaccessible without auth

**Comment by ayoubrabeh** [comment]
Thank you guys, i managed to filter the csv file and remove unwanted imports.

1. I removed uploaded links like this one: https://uploads.linear.app/9d8076c6-d3e5-4bc3-827c-2844b50d31ba/c1b4649c-f1e0-478b-bd45-6c640679caee/2b920c21-f6bf-4a8c-af2c-94e2cd5327a4
2.  Removed [x]

**Comment by tommoor** [comment]
We'll take a look at why that link wasn't exported with the signature, thanks for the report
