### ISSUE TITLE
[Feature request] Uppercase project code when copying branch name (cmd+shift+:)

### ISSUE THREAD

**Issue by carlos-santos-anchor** [linear/linear#555]
Hi team,

First of all, I love Linear 👌.  

The approach you have to keyboard power-users exposing every single keyboard shortcut impressed me so much.

I'm not sure if this is a personal preference or not, but what's your take on the generated branch name?

`proj-1337-my-feature-name-that-will-be-used-as-branch` (this is what happens today)

vs 

`PROJ-1337-my-feature-name-that-will-be-used-as-branch` (this is what I was hoping for when I used the feature the first time)

I wonder if this is just me or someone else also suggested that.

Thanks in advance.

**Comment by pekala** [comment]
Hey Carlos! 
git's relation to case sensitivity is complicated (see e.g. https://stackoverflow.com/a/38494084) so staying always lowercase is the right call IMO
