### ISSUE TITLE
503 Error when Exchanging OAuth Code for Access Token

### ISSUE THREAD

**Issue by arjunpredev** [linear/linear#559]
As mentioned in the title, when I attempt to exchange my OAuth Code for an Access Token per Linear's docs, I get a 503 error each time.

**Comment by smcgivern** [comment]
Please can you contact support directly: [https://linear.app/contact/support](https://linear.app/contact/support)

We'll need to see the full request you're sending and the response you're receiving, which we shouldn't share in a GitHub issue.

**Comment by arjunpredev** [comment]
Hi @smcgivern I received a notice from support that we need to use ngrok to test this and we've done so, however i'm still getting a 503 error when the exchange of the code for access token takes place.
