### ISSUE TITLE
Bug: Importer – Linear – Description with image is blank

### ISSUE THREAD

**Issue by mschmidtkorth** [linear/linear#561]
I'm looking to import issues from a CSV file (not Linear, but an unsupported app I have created a CSV file for).

My understanding is that Markdown URLs referencing images/files are replaced with images/files uploaded to Linear (if the URL is publicly available; as per the `replaceImagesInMarkdown` function). I'm using the "Linear" importer service.

**Expected Behavior**
Image or file from URL in description is re-uploaded to Linear and description content is updated before importing to Linear.

**Actual Behavior**
If description contains image or file URL, the description is uploaded as blank.

**Example Upload File**
```
ID,Team,Title,Description,Status,Estimate,Priority,Project ID,Project,Creator,Assignee,Labels,Created,Updated,Started,Triaged,Completed,Canceled,Archived,Due Date,DueDate,Due_Date,Parent issue,Initiatives,Project Milestone ID,Project Milestone,SLA Status,Roadmaps
abc,MyTeam,Has image,"An image: \n ![title](https://test.com/image.png) \n https://test.com/image.png",Backlog,,,,,,,,Mon May 20 2024 17:50:17 GMT+0000 (GMT),Thu Jul 25 2024 10:21:10 GMT+0000 (GMT),,,,,,Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),,,,,,
def,MyTeam,Has no image,"Some text",Backlog,,,,,,,,Mon May 20 2024 17:50:17 GMT+0000 (GMT),Thu Jul 25 2024 10:21:10 GMT+0000 (GMT),,,,,,Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),,,,,,
```

**Upload Instructions**
? Which service would you like to import from? Linear (CSV export)
? Select your exported CSV file of Linear issues EXPORTS/LINEAR_Export Tue Jul 23 2024.csv

**Result**
████████████████████████████████████████ 100% | ETA: 0s | 2/2
Linear (CSV) issues imported to your team
Does not have description with image:
<img width="562" alt="image" src="https://github.com/user-attachments/assets/b133f92c-4fef-4ec5-ae77-dd8cd70ece86">

Has description:
<img width="560" alt="image" src="https://github.com/user-attachments/assets/7b0bdc8c-b214-495d-baa5-b930c4d540bd">

---

edit: Seems this is not (yet?) supported for Linear imports. Using Pivotal (CSV) the description is filled, but without the image re-uploaded to Linear i.e. keeping the original, now non-accessible URL.

**Comment by smcgivern** [comment]
The API does handle images in Markdown, but they must be entirely on their own line:

> Note that images in markdown must be surrounded by newlines to be parsed correctly. This approach only works for image files.

[https://developers.linear.app/docs/guides/how-to-upload-a-file-to-linear#include-an-image-within-markdown-content](https://developers.linear.app/docs/guides/how-to-upload-a-file-to-linear#include-an-image-within-markdown-content)

It looks like the `replaceImagesInMarkdown` function you mention doesn't handle this, thanks for reporting!

(In a Linear export they would be on their own lines, but we can still deal with that here to avoid confusion.)

**Comment by smcgivern** [comment]
In the mean time, if you just do:

```
ID,Team,Title,Description,Status,Estimate,Priority,Project ID,Project,Creator,Assignee,Labels,Created,Updated,Started,Triaged,Completed,Canceled,Archived,Due Date,DueDate,Due_Date,Parent issue,Initiatives,Project Milestone ID,Project Milestone,SLA Status,Roadmaps
abc,MyTeam,Has image,"An image:
![title](https://test.com/image.png)
https://test.com/image.png",Backlog,,,,,,,,Mon May 20 2024 17:50:17 GMT+0000 (GMT),Thu Jul 25 2024 10:21:10 GMT+0000 (GMT),,,,,,Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),,,,,,
def,MyTeam,Has no image,"Some text",Backlog,,,,,,,,Mon May 20 2024 17:50:17 GMT+0000 (GMT),Thu Jul 25 2024 10:21:10 GMT+0000 (GMT),,,,,,Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),Sun Jul 28 2024 02:00:00 GMT+0000 (GMT),,,,,,
```

That should work.
