### ISSUE TITLE
[Feature Request]: Auto-Copy Git Branch Name When Creating an Issue

### ISSUE THREAD

**Issue by ollebergkvist** [linear/linear#581]
It would be valuable to have a configuration option that automatically copies the current Git branch name | Issue ID | Issue URL when creating a new issue (could be any issue or perhaps when you are assigned yourself). This would streamline the process, reduce the chance of errors, and ensure consistency between the branch names and the issues they relate to.

**Comment by tommoor** [comment]
Hi @ollebergkvist thanks for the request – this repo is for the SDK rather than general product requests so I'll close this out for now.
