### ISSUE TITLE
[Feature request]: Order sub-issues underneath indented underneath parent issues

### ISSUE THREAD

**Issue by rubenbullit** [linear/linear#583]
As the title states, I'd like to request a feature as toggleable option where in e.g. project issue lists sub-issues underneath the same grouping as their parent issues (grouping !== parent issue) are listed, indented under their parent issues. Or alternatively the parent issue is always included next to the issue.

**Comment by skbogner** [comment]
Hi @rubenbullit. This is something we have been tinkering with on and off. We are currently doing some technical changes that would allow something like this, but I can't promise what we end up doing yet.

**Comment by quinn-linear** [comment]
Shipped now! Check the latest changelog
