### ISSUE TITLE
Oauth Token Endpoint Failing in 503

### ISSUE THREAD

**Issue by arjunpredev** [linear/linear#584]
Hi @smcgivern I received a notice from support that we need to use ngrok to test this and we've done so, however i'm still getting a 503 error when the exchange of the code for access token takes place. I tried with Postman as well and got the same error.

**Comment by urossmolnik** [comment]
Marking as duplicate of support request.

**Comment by mukul98s** [comment]
@arjunpredev Have you find any solution? I'm facing similar issue and couldn't find anything related to this.
