### ISSUE TITLE
Issue Links are not exposed in the API

### ISSUE THREAD

**Issue by sasial-dev** [linear/linear#602]
I'm linking an issue to Discord with the `linearAPI.attachmentLinkDiscord` mutation, yet I can't seem to actually access the links in webhooks or the linear SDK itself.

**Comment by guillaumelachaud** [comment]
Hi @sasial-dev 

Did you get a successful result from the `attachmentLinkDiscord `mutation? If yes, the link should be available as an `Attachment` on your issue. You can use an `AttachmentFilter` to only get the Discord attachment on your issue:

```gql
query Issue($issueId: String!, $attachmentsFilter: AttachmentFilter) {
  issue(id: $issueId) {
    attachments(filter: $attachmentsFilter) {
      nodes {
        id
      }
    }
  }
}

"issueId": "<UUID>",
"attachmentsFilter": {
  "sourceType": {
    "eq": "discord"
  }
}
```

Let me know if you still have troubles finding the attachments on the issue after attaching a Discord link.

**Comment by sasial-dev** [comment]
This works - thank you!

**Comment by sasial-dev** [comment]
Although - @guillaumelachaud - if there is a way to set metadata from the `attachmentLinkDiscord` mutation that would be awesome.

**Comment by guillaumelachaud** [comment]
What mutation are you trying to set specifically ?

**Comment by sasial-dev** [comment]
I noticed in attachments, there's a `metadata` field with a JSON-encoded text string. I was wondering if it's possible to set that through `attachmentLinkDiscord` in the TS SDK?

**Comment by guillaumelachaud** [comment]
It's not. This metadata is not meant for public use. Linear will store some information there that are useful for rendering the attachment on the client mostly. You can read the data if you want but we don't allow adding any kind of arbitrary data.

**Comment by sasial-dev** [comment]
Thank you!
