### ISSUE TITLE
Issue in filter seems to be broken 

### ISSUE THREAD

**Issue by HolyWalley** [linear/linear#604]
Hey
Suddenly our code that works already for some time started to fail. I investigated it and it seems that issue is not in sdk, but in GraphQL schema/validation

here's the query:

```graphql
query Issue {
  issues(filter: {
    number: {
      in: [567]
    }
  }) {
    nodes {
      id
    }
  }
}
```

in Apollo explorer it fails with `Argument Validation Error`
<details>
<summary>full response</summary>

```json
{
  "errors": [
    {
      "message": "Argument Validation Error",
      "path": [
        "issues"
      ],
      "locations": [
        {
          "line": 14,
          "column": 3
        }
      ],
      "extensions": {
        "code": "INVALID_INPUT",
        "type": "invalid input",
        "userError": true,
        "meta": {}
      }
    }
  ],
  "data": null
}
```
</details>

When I'm trying the same query, but instead of `in: [567]` I provide `eq: 567` it works fine. `nin` filter for `Issue number` fails the same way

It started failing on sdk v26.0.0, I updated it to v30.0.0 - same result

**Comment by smcgivern** [comment]
Thanks for reporting this, we should have a fix out soon.
