### ISSUE TITLE
Pivotal Importer does not import estimates

### ISSUE THREAD

**Issue by maplealmond** [linear/linear#606]
The pivotal importer sets all estimates to null.

The following line is suspect

`// const priority = parseInt(row['Estimate']) || undefined;`

> An estimate in pivotal is not priority, but rather point complexity.

**Comment by guillaumelachaud** [comment]
That line is suspicious indeed 🤔 . Looks like it's been commented out since the initial implementation of the importer. Thanks for pointing it out, we can put up a fix for this.
