### ISSUE TITLE
Query fails when querying projects using the SDK

### ISSUE THREAD

**Issue by matthewclso** [linear/linear#619]
Using the SDK -
```
await linearClient.projects();
```
I encounter the following error -
```
rejected promise not handled within 1 second: Error: Cannot query field "milestone" on type "Project".
extensionHostProcess.js:162
stack trace: Error: Cannot query field "milestone" on type "Project".
    at parseLinearError (/home/ubuntu/linear-issues/node_modules/@linear/sdk/src/error.ts:232:10)
    at /home/ubuntu/linear-issues/node_modules/@linear/sdk/src/client.ts:65:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by guillaumelachaud** [comment]
Hi @matthewclso 

Can you share the version number of the SDK you are using? Thanks!

**Comment by matthewclso** [comment]
Hi @guillaumelachaud !  I'm using the latest version 32.0.0, installed via `npm`.

**Comment by guillaumelachaud** [comment]
🤔 That's odd, we don't have this field in any of our query fragments in the generated SDK.

It was removed from the SDK on Feb 15, 2023, as part of release [2.2.0](https://github.com/linear/linear/releases/tag/%40linear%2Fsdk%402.2.0)

```
feat(schema): [breaking] Field 'milestone' (deprecated) was removed from object type 'Project' (Project.milestone)
```

**Comment by matthewclso** [comment]
Ah, I was just being dumb!  I thought I had the latest version installed but turns out my `package.json` had a much older version specified.  Sorry for the trouble!
