### ISSUE TITLE
[Bug] Import from Trello fails due to `TypeError: data.checklists is not iterable`

### ISSUE THREAD

**Issue by chaupow** [linear/linear#622]
Hello 👋 
I'm currently trying to migrate from Trello to LInear but fail to import the data.

Installed the linear-importer with 
```
npm i --location=global @linear/import
```

This is the error message I get:
```
❯ linear-import
? Input your Linear API key (https://linear.app/settings/api) <blubb>
? Which service would you like to import from? Trello (JSON export)
? Select your exported JSON file of Trello cards chau_test/chau_test.json
? Would you like to map Trello lists to statuses? Yes
? Would you like to discard the archived cards? No
? Would you like to discard the (possibly unarchived) cards within archived lists? No
TypeError: data.checklists is not iterable
    at TrelloJsonImporter.<anonymous> (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:1247:42)
    at Generator.next (<anonymous>)
    at /opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:71:12)
    at TrelloJsonImporter.import (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:1236:29)
    at /opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:162:45
    at Generator.next (<anonymous>)
    at /opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:71:12)
    at importIssues (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:159:44)
    at /opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:1452:19
    at Generator.next (<anonymous>)
    at fulfilled (/opt/homebrew/lib/node_modules/@linear/import/dist/cli.js:72:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I can reproduce it with a tiny test table as well: [chau_test.json](https://github.com/user-attachments/files/17773290/chau_test.json)

Any hints on how to fix this would be highly appreciated!

**Comment by chaupow** [comment]
Wow, thanks so much for the quick fix! ✨ 
I can now import successfully but it seems like checklists and comments are not imported correctly. I don't know if that is a regression caused by the fix or is an unrelated problem.

Here's how the trello ticket looks like:
![Image](https://github.com/user-attachments/assets/432691fc-2542-4d00-8a0d-11249dd6f2ad)

This is the imported linear ticket:
![Image](https://github.com/user-attachments/assets/c1c84f1a-afd6-4396-ae1b-412e1a312d06)

According to this PR description it seems like both the checklist as well as the comment should be part of the ticket:
https://github.com/linear/linear/pull/124

I've imported this with using the linear commit `1e91bc1ee93aead4a6fbab73b219cd8adc16c753`
and this is the updated minimal test JSON that has checklist items as well as a comment:

[chau_test.json](https://github.com/user-attachments/files/17836169/chau_test.json)

**Comment by chaupow** [comment]
As I cannot reopen the issue, tagging @guillaumelachaud for visibility 🙏 I hope that's ok! 
Let me know if I should open a new issue instead 😊

**Comment by guillaumelachaud** [comment]
It looks like your JSON file uses a slightly different schema for checklists 🤔. Do you use the Advanced Checklists feature? How did you export the data from Trello ?

**Comment by chaupow** [comment]
Hmm good question - I wasn't aware there is an advanced checklist feature but we can set due dates, so I guess that means we are using advanced checklists? From a quick skim I don't find a way to make them non-advanced though.

This is how I get the JSON file:

![Image](https://github.com/user-attachments/assets/32db4d06-923f-45a1-ab95-f03b3830a7ab)

**Comment by chaupow** [comment]
But the comment import is also not working so I don't think it's just the advanced/non-advanced checklist 🤔 
Either I export the data incorrectly or they changed the format.

**Comment by chaupow** [comment]
@guillaumelachaud do you think this is something that can be addressed in the next few days or will this stay like this longer?

I'm currently trying to figure out if we should try and copy everything manually or if it's worth waiting and staying on trello for a bit longer.

**Comment by guillaumelachaud** [comment]
It is possible that Premium Trello comes with a different schema, but I haven't checked myself to confirm. Also, I didn't find good documentation about the schema, so it's a bit hard be completely sure.

Looking at your screenshots, it looks like you are exporting the entire workspace. Can you try exporting boards individually? It should be available as an option in the main board menu:

![Image](https://github.com/user-attachments/assets/5534e1a6-1e72-4868-8d87-fd8731bddedf)

**Comment by chaupow** [comment]
OMG @guillaumelachaud that was it! When exporting from the board, it works and imports as it should, including checklists and comments 😭❤ 

Thanks so much and sorry for the confusion. Maybe worth mentioning this somewhere in the docs? Either way, thanks a lot!!!
