### ISSUE TITLE
Pivotal CSV import fails with 'A label with this name already exists'

### ISSUE THREAD

**Issue by alexreid** [linear/linear#624]
With linear-import 2.2.0, attempting to import a Pivotal export CSV fails as it attempts to create labels multiple times. 

Investigating a bit, this seems to be because Pivotal's CSV exports separate labels with `, ` (comma followed by a space), but the Pivotal importer expects labels to be separated with `,` (just a comma). So if you have two Pivotal stories, with these labels:

Story A labels: `foo`
Story B labels: `bar, foo`

The importer will create the label `foo`, and then attempt to create a label ` foo` (note preceding space). This is then rejected as a duplicate (presumably Linear itself trims leading whitespace from labels as they're created).

I should be able to work around it by reformatting the Pivotal CSV to remove the extra spaces, but it seems likely someone else will run into this issue with Pivotal's impending shutdown!

**Comment by fortinmike** [comment]
For my first project import the proposed workaround worked, but importing a second project containing some of the same tags (and cleaned up in the same manner to remove unwanted spaces) again results in duplicate tag errors. Are multiple projects using the same tags not allowed by the importer? Currently I'm unable to import any project beyond my first import which created a few dozen labels, many of which are reused across projects.

I tried the master branch with commit 1e91bc1ee93aead4a6fbab73b219cd8adc16c753 that is supposed to fix the issue, but the same thing happens. Any insight?

**Comment by mufeez-amjad** [comment]
Hi @fortinmike, I'm able to reproduce with your specific case – will put up a PR and tag you here when it's been released.

**Comment by fortinmike** [comment]
Thanks for the super-quick support @mufeez-amjad ! It's kind of a blocker for our potential migration to Linear so I'll try your fix as soon as it's available and report back.

**Comment by mufeez-amjad** [comment]
@fortinmike, can you try importing with [@linear/import@2.2.2](https://github.com/linear/linear/releases/tag/%40linear%2Fimport%402.2.2)? Should be fixed in that version.

**Comment by fortinmike** [comment]
@mufeez-amjad Works great, thanks! 👍
