### ISSUE TITLE
Pressing "escape" while in an issue should not exit the issue

### ISSUE THREAD

**Issue by zsiegel92** [linear/linear#635]
Pressing "escape" triggers a browser navigation event. When typing text I compulsively press escape and I suspect I'm not the only one who has wondered why this triggers a "back" navigation.

If there's a good reason for this then by all means keep it and close this issue. In general I think capturing keyboard events should be done sparingly.

Thanks so much!

**Comment by urossmolnik** [comment]
Hi, could you share on which view does this happens? A short video or screenshot would be helpful.

This is an expected behavior in Inbox and Triage views where split view is used.

**Comment by zsiegel92** [comment]
Hi @urossmolnik thanks for the response.

The URL of the view where this happens is `https://linear.app/<org name>/issue/<org prefix>-<issue number>/<issue slug>`

I.e. the view where you view an issue.

Before I take a video and go through the trouble to blur things, I wonder whether you can just confirm whether the behavior I described is expected. That is, when I press "escape", it takes me back to my issues.

Note: this is not the inbox split view, though I do notice that Linear uses the same URL for viewing an issue in both inbox split view and alone.

**Comment by urossmolnik** [comment]
Totally missed this. Confirming we generally handle this as a back navigation, so no video needed.

We will take this as a feedback but at this point don't plan to do any changes to to it.
