### ISSUE TITLE
OAuth 2.0 `invalid_client` error

### ISSUE THREAD

**Issue by kzkr** [linear/linear#636]
### Description:

I'm encountering an `invalid_client` error during the OAuth 2.0 flow when integrating Linear's API in my Nuxt 3 application. This issue is similar to [Issue #264](https://github.com/linear/linear/issues/264), but instead of a Flutter app, I'm using a Nuxt 3 application.

### Steps to reproduce:

- Create a Nuxt 3 application.
- Implement OAuth 2.0 authentication flow as described in [Linear's OAuth documentation](https://developers.linear.app/docs/oauth/authentication).
- Register the application in Linear with the correct redirect URI and client credentials.
- Generate the authorization code by redirecting to Linear's authorization URL (this step works perfectly).
- Attempt to exchange the authorization code for an access token.

### Observed Behavior:

The token exchange step returns the following error:

```
{
    "error": "invalid_client",
    "error_description": "Invalid client: cannot retrieve client credentials"
}
```

### Expected Behavior:

The exchange should successfully return an access token.

### Environment:

Application: Nuxt 3.14
OAuth Flow: Authorization Code Flow
Node: v22.11.0

### Troubleshooting steps taken:

- Verified `client_id` and `client_secret` are correct.
- Confirmed the redirect URI matches between Linear application settings and OAuth request.
- Checked the token endpoint URL and ensured it's correct.
- Ensured all required headers (e.g., `Content-Type: application/x-www-form-urlencoded`) are included in the request.
- Verified requested scopes align with the application settings.

Despite these efforts, the issue persists.

Thanks for your help!

**Comment by urossmolnik** [comment]
Hi, do you have visibility into request made when requesting token on `/token` endpoint?

Is it `application/x-www-form-urlencoded` request as specified at [https://developers.linear.app/docs/oauth/authentication#id-4.-exchange-code-for-an-access-token](https://developers.linear.app/docs/oauth/authentication#id-4.-exchange-code-for-an-access-token)?

**Comment by kzkr** [comment]
Yes, and yes. 

I'm basically performing a simple fetch like that, with the right `code`, `redirect_uri`, `client_id`, `client_secret`, and `grant_type`.

```
const URL = `https://api.linear.app/oauth/token?code=${code}&redirect_uri=${redirect_uri}&client_id=${client_id}&client_secret=${client_secret}&grant_type=authorization_code`

const res = await $fetch(URL, {
    method: "POST",
    headers: {
        "Content-Type": "application/x-www-form-urlencoded",
    },
});
```
I received the code from the first call to `https://linear.app/oauth/authorize?client_id=${client_id}&redirect_uri=${redirect_uri}&scope=read,write&response_type=code`

I copied the `client_id` and `client_secret` from the Linear OAuth app settings. 

Here you can see a screenshot of the request headers:

![Image](https://github.com/user-attachments/assets/f6c77385-32a8-4724-9aa2-d5ca1007e6e3)

Thanks!

**Comment by urossmolnik** [comment]
I think you will need to pass data in body and not in query params when doing a `application/x-www-form-urlencoded` content type request.

[https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#url-encoded_form_submission](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#url-encoded_form_submission)

**Comment by kzkr** [comment]
Absolutely! 🤦‍♂️

Adding this clarification to the [OAuth documentation](https://developers.linear.app/docs/oauth/authentication) would definitely help other developers avoid similar issues.

Thank you for your quick response and assistance, @urossmolnik. The issue is now resolved, so I'll go ahead and close it.

Cheers! 🙌

**Comment by urossmolnik** [comment]
Glad this helped. We'll add a note to our docs.
