### ISSUE TITLE
OAuth Endpoint Returns 503 on First Request and 400 on Subsequent Requests

### ISSUE THREAD

**Issue by mukul98s** [linear/linear#637]
I'm encountering an issue where the OAuth token endpoint does not return the expected `access_token` response. Despite verifying all the credentials and configurations, the endpoint behaves inconsistently. 

1. **First request**: Returns a `503 Service Unavailable` status code.  
2. **Subsequent requests**: Return a `400 Bad Request` status code with the following JSON payload:  
   ```json
   {
       "error": "invalid_grant",
       "error_description": "Invalid grant: authorization code is invalid"
   }
   ```

#### Expected Behavior:
The OAuth token endpoint should respond with a valid `access_token` when provided with correct credentials, a valid `authorization_code`, and a properly formatted request.

#### Actual Behavior:
- The first request to the endpoint returns a `503 Service Unavailable`.  
- Retrying the same request results in a `400 Bad Request` with an error indicating that the `authorization_code` is invalid.  

#### Debugging Steps Taken:
1. Verified all secrets, including `client_id`, `client_secret`, and `authorization_code`.
2. Confirmed that the `redirect_uri` matches the one registered with the OAuth provider and used in the previous step
3. Ensured the request is sent with the correct `Content-Type` header:
   ```
   Content-Type: application/x-www-form-urlencoded
   ```
4. Double-checked the request payload for correct parameters:
   ```
   grant_type=authorization_code
   code=<authorization_code>
   redirect_uri=<redirect_uri>
   client_id=<client_id>
   client_secret=<client_secret>
   ```
5. Validated the endpoint URL and ensured it is accessible.

#### Impact:
This issue blocks the OAuth authentication flow, making it impossible to retrieve access tokens for users. It affects both application functionality and user experience.

#### Additional Information:
- Request Headers:
  ```
  Content-Type: application/x-www-form-urlencoded
  ```
- Response (First Request): `503 Service Unavailable`
- Response (Retry):  
  ```json
  {
      "error": "invalid_grant",
      "error_description": "Invalid grant: authorization code is invalid"
  }
  ```

Please investigate and advise on resolving this issue.

**Comment by smcgivern** [comment]
@mukul98s how are you sending the params? They must be in the request body; see this similar report from earlier this week: https://github.com/linear/linear/issues/636#issuecomment-2503049513

**Comment by smcgivern** [comment]
If that's not it, could you please provide the actual HTTP request you're making or a way to reproduce it exactly (feel free to email support)? I cannot reproduce this with curl:

```bash
curl https://api.linear.app/oauth/token -d "grant_type=authorization_code&code=$code&client_id=$client_id&client_secret=$client_secret&redirect_uri=$redirect_uri"
```

**Comment by mukul98s** [comment]
I'm sending them via the body. I have already checked #636 . 

It shows the same error when used with Postman. 

![Image](https://github.com/user-attachments/assets/be8dbc9c-2394-4e94-a3eb-59df7d1aa37c)

**Comment by mukul98s** [comment]
@smcgivern It's returns the same response even with curl.

**Comment by smcgivern** [comment]
First of all, the `redirect_uri` cannot be `localhost` - this will fail with a different error though:

```
{"error":"invalid_request","error_description":"Invalid request: `redirect_uri` is invalid"}
```

I am actually confused about how you even obtained the code in the first place. When I enter a localhost URL for the callback, and then visit [https://linear.app/oauth/authorize](https://linear.app/oauth/authorize) with that client ID, I just get this error (as expected):

<img src="https://uploads.linear.app/6ee3ee0f-1ea6-4b88-a969-f63432eeb657/de82a1dd-00e5-4c8b-8f4c-354db2e0ee87/602ebaca-46a8-4fb0-b0ed-422447e835e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzZlZTNlZTBmLTFlYTYtNGI4OC1hOTY5LWY2MzQzMmVlYjY1Ny9kZTgyYTFkZC0wMGU1LTRjOGItOGY0Yy0zNTRkYjJlMGVlODcvNjAyZWJhY2EtNDZhOC00ZmIwLWIwZWQtNDIyNDQ3ZTgzNWU0IiwiaWF0IjoxNzMyODg5MTI2LCJleHAiOjMzMzAzNDQ5MTI2fQ.86PHfgcUzJd64LtcTPvDr2MY_qbLpMuLq3oZ_h7VHf8 " alt="image.png" width="499" height="265" />

**Comment by mukul98s** [comment]
I'll test it with ngrok and let you know. I'm not familiar with the localhost error, and the endpoint didn't return any errors either.

**Comment by mukul98s** [comment]
https://linear.app/oauth/authorize?actor=application&client_id=$client_id&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Flinear%2Fcallback%2F&response_type=code&scope=read%2Cwrite%2Cissues%3Acreate%2Ccomments%3Acreate%2CtimeSchedule%3Awrite%2Cadmin&state=xdv6FeZsnf

This is the constructed url. 

I tried the curl command in two ways
1. One you have mentioned in the above comment.
```
curl https://api.linear.app/oauth/token -d "grant_type=authorization_code&code=$code&client_id=$client_id&client_secret=$client_secret&redirect_uri=$redirect_uri"
```
2. Second is generated by the Postman with header 
```
curl --location 'https://api.linear.app/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'code=$code' \
--data-urlencode 'redirect_uri=http://localhost:3000/auth/linear/callback/' \
--data-urlencode 'client_id=$client_id' \
--data-urlencode 'client_secret=$client_secret' \
--data-urlencode 'grant_type=authorization_code'
```

**Comment by smcgivern** [comment]
Thank you, I can see the problem: the `timeSchedule:write` scope will generate an error on our side when we try to persist the token, but by then the authorisation code has been consumed.

I will fix this, but in the mean time, unless you need that scope (which you don't; you already have overlapping scopes), you can remove it and this should succeed 🙂

**Comment by mukul98s** [comment]
Yes it is working now. Thanks for the help.
