### ISSUE TITLE
How to retrieve project milestone status using API?

### ISSUE THREAD

**Issue by dvlkv** [linear/linear#638]
I want to retrieve project milestone status using API. 
![Image](https://github.com/user-attachments/assets/57f5af93-9d51-4eef-bdf9-9be49bd2984c)
I've found out that there is [currentProgress: JSONObject!](https://github.com/dvlkv/linear/blob/2f084bcb553a6edd1a393f7393ee28dbd00fd02c/packages/sdk/src/schema.graphql#L19173-L19174) field in schema.  
However, this field is marked as "Internal" and has ```JSONObject``` type.  
  
Is there any another way to get this from milestone? Do you have plans to provide this status to public?

**Comment by suevalov** [comment]
Hi! Currently, there's no way to retrieve this information via the API, but I think it makes sense to add it to the ProjectMilestone GraphQL object. I'll take a look and let you know once it is ready.

**Comment by suevalov** [comment]
@dvlkv there should be 2 new fields on the ProjectMilestone object: `status` and `progress`

**Comment by dvlkv** [comment]
@suevalov glad to hear that, thank you! Do you have an estimate for the release?
