### ISSUE TITLE
Feature Request: Allow multiple users to be assigned to an issue

### ISSUE THREAD

**Issue by clarxyg** [linear/linear#643]
Currently, it is possible for only one user to be assigned to the issue, and for additional users to work on it, subtasks need to be created.

**Comment by quinn-linear** [comment]
It's not in our near-term plans to change this, the thinking behind it is we believe ownership of an issue should fall to one person. That said, there are cases where there is a need for more assignees, like pair-programming, so it's on our radar to look into in the future for scenarios like that.

For now, as you mentioned sub-issues are the best way to delegate, or by adding members as subscribers to the issue.
