### ISSUE TITLE
Better CLI argument handling

### ISSUE THREAD

**Issue by NuroDev** [linear/linear#79]
Would be nice if the ability was added to pass in tokens via flags. EG:
```bash
linear-import -t xxxxxx --github-token xxxxxx
```
Just a nice QoL improvement when setting up a new workspace and importing multiple repositories issues having to manually copy paste in tokens manually each time 🙂

**Comment by rlargman** [comment]
We don't currently have plans to change this functionality, but I've noted your feedback!
