### ISSUE TITLE
Make imports idempotent

### ISSUE THREAD

**Issue by boydgreenfield** [linear/linear#81]
Currently, if the Linear API returns a 500/503, there's a connection error, etc. the import halts midway through. 

Unfortunately, this is a _significant_ inconvenience when importing multiple Github repos to a single team (it probably is less painful for other CSV-based importers).

It'd be very nice to have the importer: 
* First load existing issues for a given team _from Linear_
* Check if an issue has already been imported
* Import _only if it has not_

This could probably be accomplished by simply looking for the string the importer injects into the issue body, e.g., `[View original issue in GitHub](URL)`.

**Comment by rlargman** [comment]
The newer built in importer within Linear is idempotent, and will not import the same issues multiple times. I would suggest trying out the new importer for that functionality. We don't currently have plans to add this functionality to the CSV importer.
